import * as THREE from 'three';
import {BOSSES} from './data.js';
/* All activities use direct clicks or a pointer-controlled tray. No walking or pointer lock. */
export class Activities{
 constructor(state,world){this.state=state;this.world=world;this.active=null;this.objects=[];this.event=null;this.eventObjects=[];this.nextEvent=Date.now()+90000;state.on((type,r)=>{if(type==='interact')this.interact(r);});}
 clear(){this.objects.forEach(o=>this.world.removeTarget(o));this.objects=[];this.active=null;this.state.emit('activity',null);}
 leave(){this.clear();this.world.teleport('lab');}
 object(g,action,data,label){this.objects.push(g);this.world.addTarget(g,action,data,label);return g;}
 start(kind){this.clear();this.world.teleport(kind);const now=Date.now(),w=this.world;this.active={kind,start:now,end:now+(kind==='memory'?180000:kind==='parkour'?45000:kind==='boss'?60000:30000),score:0,items:[],spawn:0,falls:0};const a=this.active;
 if(kind==='target'){for(let i=0;i<5;i++){const g=new THREE.Group();w.cylinder(g,0,.35,0,.85,.3,'#62b7c1');w.ring(g,0,.53,0,.55,'#eaf7d6');this.object(g,'target',i,'Click target');this.retarget(g);a.items.push(g);}}
 if(kind==='memory'){a.sequence=[];a.index=0;a.round=0;a.phase='wait';a.next=now+600;['#71adb2','#a595bc','#d6b160','#7baf7a'].forEach((color,i)=>{const g=new THREE.Group();g.position.set(34+(i%2?3:-3),0,70+(i<2?-3:3));w.box(g,0,.3,0,4,.5,3.5,color);g.children[0].material=g.children[0].material.clone();w.label(g,String(i+1),0,.9,0,1.3);this.object(g,'memory',i,'Panel '+(i+1));a.items.push(g);});this.memoryNext();}
 if(kind==='parkour'){a.step=0;a.phaseStart=now;const coords=[[-7,3],[-3,3],[1,3],[5,3],[7,0],[3,0],[-1,0],[-5,0],[-7,-3],[-3,-3],[1,-3],[5,-3]];coords.forEach(([x,z],i)=>{const g=new THREE.Group();g.position.set(108+x,0,70+z);w.box(g,0,.2,0,2.5,.4,2,'#a9ae8d');w.label(g,String(i+1),0,.7,0,1.15);this.object(g,'relay',i,'Relay '+(i+1));a.items.push(g);});}
 if(kind==='boss'){a.tier=this.state.s.stats.bosses;a.name=BOSSES[Math.min(6,a.tier)]+(a.tier>6?' '+(a.tier-5):'');a.max=Math.max(100,this.state.manual*35+this.state.cps*8)*(1+a.tier*.2)*(1+this.state.s.reality);a.hp=a.max;a.warning=false;a.nextAttack=now+6000;const g=new THREE.Group();g.position.set(-34,1.4,68);w.sphere(g,0,0,0,1.6,'#aa798f');for(let i=0;i<3;i++)w.ring(g,0,0,0,2+i*.25,'#d9b2b1',i*.7);this.object(g,'boss',null,'Attack '+a.name);a.boss=g;const shield=new THREE.Group();shield.position.set(-34,0,75);w.cylinder(shield,0,.35,0,1.4,.6,'#7c9da6');w.label(shield,'SHIELD',0,1.2,0,3.2);this.object(shield,'shield',null,'Activate shield when the attack warning appears');a.shield=shield;}
 this.state.emit('activity',a);this.state.notice({target:'Click targets: blue +1, purple +3, gold +10, red −3.',memory:'Watch the four panels, then click them in the same order.',catch:'Move your pointer or finger to guide the tray under falling crystals.',parkour:'Click the numbered relays in order when the next one turns green.',boss:'Click the boss to attack. Click SHIELD when an attack warning appears.'}[kind]);}
 retarget(g){const r=Math.random(),type=r<.12?'red':r<.2?'gold':r<.4?'purple':'blue';g.userData.type=type;g.children[0].material=this.world.mat({red:'#c77b78',gold:'#d9b251',purple:'#a18bbe',blue:'#68acbb'}[type]);g.position.set((Math.random()-.5)*15,0,70+(Math.random()-.5)*11);}
 memoryNext(){const a=this.active;if(!a||a.kind!=='memory')return;a.round++;a.sequence.push(Math.floor(Math.random()*4));a.index=0;a.showIndex=0;a.phase='show';a.next=Date.now()+600;a.lit=-1;}
 lightPanel(index){const a=this.active;if(!a||a.kind!=='memory')return;a.items.forEach((g,i)=>{const mat=g.children[0].material;mat.emissive.set(i===index?'#f0e9bc':'#000000');mat.emissiveIntensity=i===index?.6:0;g.children[0].scale.y=i===index?.9:.5;});a.lit=index;}
 interact(r){if(r.action==='event'){this.collectEvent(r.data);return;}const a=this.active;if(!a||Date.now()>a.end)return;if(r.action==='target'&&a.kind==='target'){const g=a.items[r.data];a.score=Math.max(0,a.score+({blue:1,purple:3,gold:10,red:-3}[g.userData.type]));this.world.burst(g.position,'#f5e7bc',7);this.retarget(g);this.state.emit('sound',500);}
 if(r.action==='memory'&&a.kind==='memory'&&a.phase==='input'){const i=r.data;this.lightPanel(i);a.unlight=Date.now()+180;this.state.emit('sound',300+i*150);if(i!==a.sequence[a.index]){this.state.s.stats.memory=Math.max(this.state.s.stats.memory,a.round-1);this.finish((a.round-1)*4,`${a.round-1} sequences completed.`);return;}a.index++;if(a.index===a.sequence.length){this.state.s.stats.memory=Math.max(this.state.s.stats.memory,a.round);if(a.round===8)this.finish(40,'Perfect stabilisation. All eight sequences completed.');else{a.phase='wait';a.next=Date.now()+600;}}}
 if(r.action==='relay'&&a.kind==='parkour'){const safe=(Date.now()-a.phaseStart)%1400<900;if(r.data!==a.step||!safe){a.end-=2000;this.state.notice('Wait for the next green relay. −2 seconds.');return;}a.items[a.step].children[0].material=this.world.mat('#679580');a.step++;a.score=a.step*3;this.state.emit('sound',350+a.step*30);if(a.step===12){const sec=(Date.now()-a.start)/1000;this.state.s.stats.parkour=this.state.s.stats.parkour?Math.min(sec,this.state.s.stats.parkour):sec;this.finish(Math.max(15,45-Math.floor(sec/2)),`All 12 relays linked in ${sec.toFixed(1)} seconds.`);}}
 if(r.action==='shield'&&a.kind==='boss'&&a.warning){a.warning=false;a.nextAttack=Date.now()+6000;this.state.notice('Attack blocked');this.state.emit('sound',650);}
 if(r.action==='boss'&&a.kind==='boss'){a.hp-=(this.state.manual+this.state.cps*.15)*(1+(this.state.fx.bossDamage||0));this.world.burst(a.boss.position,'#e5c599',6);this.state.emit('sound',140);if(a.hp<=0){this.state.s.stats.bosses++;this.state.q('boss');this.state.s.cores++;this.state.s.coreTotal++;this.state.addPoints(2);this.state.s.dust+=10;this.finish(25,'Boss defeated · +1 Quantum Core · +2 Skill Points · +10 stardust');}}}
 finish(score,message){const kind=this.active?.kind;if(!kind)return;this.state.s.stats.games++;if(score>0)this.state.s.stats.wins++;this.state.q('game');const tokens=Math.max(0,Math.min(40,Math.floor(score))),energy=Math.max(100,this.state.cps*3)*Math.min(60,score);this.state.s.tokens+=tokens;this.state.gain(energy);this.state.xp(Math.min(250,score*5));this.clear();this.state.progress();this.state.save();this.state.emit('result',{kind,score,tokens,energy,message});}
 spawnEvent(){if(this.event||this.active||this.state.s.lifetime<500)return;const types=['surge','storm','golden',...(this.state.s.rebirths?['invasion']:[])],kind=types[Math.floor(Math.random()*types.length)];this.event={kind,end:Date.now()+45000,left:kind==='storm'?5:kind==='invasion'?4:1};if(kind==='surge'){this.state.addBoost('passive',5,30);this.event.end=Date.now()+30000;this.state.notice('Power surge · 5× production for 30 seconds');return;}for(let i=0;i<this.event.left;i++){const g=new THREE.Group();g.position.set(-3+i*1.8,1,1.5);this.world.sphere(g,0,0,0,.4,kind==='invasion'?'#a48ab3':'#dfbc66');this.world.ring(g,0,0,0,.65,kind==='invasion'?'#b69ac4':'#edd697');this.world.addTarget(g,'event',i,kind==='invasion'?'Disrupt void anchor':'Collect bonus energy');this.eventObjects.push(g);}this.state.notice(kind==='invasion'?'Void anchors appeared in Origin. Click all four.':'Bonus visitors appeared near the energy core. Click to collect.');}
 collectEvent(i){const e=this.event,g=this.eventObjects[i];if(!e||!g||!g.visible||e.end<Date.now())return;g.visible=false;e.left--;this.state.gain(Math.max(500,this.state.cps*30)*(1+(this.state.fx.rare||0)));this.world.burst(g.position,'#e5c380',8);if(e.left===0){this.state.s.stats.events++;this.state.s.dust+=e.kind==='invasion'?20:5;if(e.kind==='invasion')this.state.unlockSkin('void');this.state.notice('Event complete · energy and stardust collected');this.clearEvent();}}
 clearEvent(){this.eventObjects.forEach(o=>this.world.removeTarget(o));this.eventObjects=[];this.event=null;}
 update(dt){const now=Date.now(),a=this.active,w=this.world;if(a){if(now>=a.end){this.finish(['target','catch','parkour'].includes(a.kind)?a.score:0,a.kind==='boss'?'The boss escaped.':`Time is up. ${a.score} points scored.`);return;}
 if(a.kind==='memory'){if(a.unlight&&now>a.unlight){this.lightPanel(-1);a.unlight=0;}if(now>=a.next){if(a.phase==='show'){if(a.lit>=0){this.lightPanel(-1);a.next=now+240;}else if(a.showIndex<a.sequence.length){this.lightPanel(a.sequence[a.showIndex++]);this.state.emit('sound',300+a.lit*150);a.next=now+650;}else{a.phase='input';a.next=Infinity;}}else if(a.phase==='wait')this.memoryNext();}}
 if(a.kind==='catch'){a.spawn-=dt;if(a.spawn<=0){a.spawn=.5;const r=Math.random(),value=r<.02?15:r<.1?8:r<.25?5:1;const m=new THREE.Mesh(new THREE.OctahedronGeometry(.35),w.mat(value===15?'#a28bb7':value===8?'#a5c7cb':value===5?'#d8b566':'#86bca0'));m.position.set(68+(Math.random()-.5)*15,5.5,70+(Math.random()-.5)*11);w.scene.add(m);this.objects.push(m);a.items.push({m,value});}a.items=a.items.filter(item=>{item.m.position.y-=dt*2.4;item.m.rotation.y+=dt;const p=item.m.position;if(p.y<.8&&Math.abs(p.x-w.player.x)<1.5&&Math.abs(p.z-w.player.z)<1.3){a.score+=item.value;w.scene.remove(item.m);return false;}if(p.y<0){w.scene.remove(item.m);return false;}return true;});}
 if(a.kind==='parkour'){const safe=(now-a.phaseStart)%1400<900;a.items.forEach((g,i)=>g.children[0].material=w.mat(i<a.step?'#7fa58c':i===a.step?safe?'#90c77d':'#ddb85e':'#bbb79a'));}
 if(a.kind==='boss'){a.boss.rotation.y+=dt*.35;if(!a.warning&&now>a.nextAttack){a.warning=true;a.warningEnd=now+2000;}if(a.warning&&now>a.warningEnd){a.warning=false;a.end-=3000;a.nextAttack=now+6000;this.state.notice('Attack hit · −3 seconds. Click SHIELD during warnings.');}a.shield.children[0].material=w.mat(a.warning?'#ddb55e':'#7c9da6');}}
 if(now>this.nextEvent){this.spawnEvent();this.nextEvent=now+90000+Math.random()*60000;}if(this.event){if(now>this.event.end)this.clearEvent();else this.eventObjects.forEach(g=>g.rotation.y+=dt*.5);}}
}
