import * as THREE from 'three';
import {BOSSES} from './data.js';
export class Activities{
 constructor(state,world){this.state=state;this.world=world;this.active=null;this.objects=[];this.event=null;this.eventObjects=[];this.nextEvent=Date.now()+90000;this.eventCooldown=0;state.on((type,data)=>{if(type==='interact')this.interact(data);if(type==='fall'&&this.active?.kind==='parkour'){this.active.falls++;state.notice('Back to the start. The timer is still running.');}});}
 clear(){this.objects.forEach(o=>this.world.removeTarget(o));this.objects=[];this.active=null;this.world.parkourPlatforms.forEach(p=>{p.disabled=false;p.mesh.visible=true;p.stood=0;});this.state.emit('activity',null);}
 leave(){this.clear();this.world.teleport('lab');}
 object(g,action,data,label,range=60){this.objects.push(g);this.world.addTarget(g,action,data,label,range);return g;}
 start(kind){this.clear();this.world.teleport(kind);this.active={kind,score:0,start:Date.now(),end:Date.now()+(kind==='parkour'?90000:kind==='boss'?60000:30000),spawn:0,items:[],falls:0};const a=this.active,w=this.world;
 if(kind==='target'){for(let i=0;i<5;i++){const g=new THREE.Group();const disk=w.cylinder(g,0,0,0,.55,.12,'#75d9f3');disk.rotation.x=Math.PI/2;w.ring(g,0,0,.08,.4,'#c4f4ff',0);w.sphere(g,0,0,.1,.09,'#efffff',true);this.object(g,'target',i,'Hit energy target');this.retarget(g);a.items.push(g);}}
 if(kind==='memory'){a.sequence=[];a.index=0;a.round=0;a.phase='wait';a.next=Date.now()+600;a.end=Infinity;['#73dbe9','#b89bf8','#f2c776','#81e7b7'].forEach((c,i)=>{const g=new THREE.Group();g.position.set(34-4.5+i*3,1.7,65);w.box(g,0,0,0,2,2,.4,c,true);w.label(g,String(i+1),0,1.5,0,2,c);g.children[0].material=g.children[0].material.clone();g.children[0].material.emissiveIntensity=0;this.object(g,'memory',i,'Activate panel '+(i+1));a.items.push(g);});this.memoryNext();}
 if(kind==='boss'){a.tier=this.state.s.stats.bosses;a.name=BOSSES[Math.min(6,a.tier)]+(a.tier>6?' '+(a.tier-5):'');a.max=Math.max(100,this.state.manual*35+this.state.cps*8)*(1+a.tier*.2)*(1+this.state.s.reality);a.hp=a.max;const g=new THREE.Group();g.position.set(-34,2.3,66);w.sphere(g,0,0,0,1.15,'#e27d99',true);for(let i=0;i<3;i++)w.ring(g,0,0,0,1.7+i*.2,'#ffb5cc',i*.7);g.scale.setScalar(1+Math.min(1.5,a.tier*.12));this.object(g,'boss',null,'Attack '+a.name,30);a.boss=g;a.lastHit=0;const beam=w.box(w.scene,-34,.5,70,18,.10,.1,'#ff9bba',true);a.beam=beam;this.objects.push(beam);}
 this.state.emit('activity',a);this.state.notice({target:'30 seconds · Blue +1, purple +3, gold +10, red −3',memory:'Watch the control panels, then repeat their sequence.',catch:'30 seconds · Walk into falling energy crystals to catch them.',parkour:'90 seconds · Sprint and jump between platforms. Avoid rotating lasers.',boss:'60 seconds · Attack the core and jump over its rotating beam.'}[kind]);}
 retarget(g){const r=Math.random(),type=r<.12?'red':r<.2?'gold':r<.4?'purple':'blue';g.userData.type=type;g.children[0].material=this.world.mat({red:'#ec7785',gold:'#ffd471',purple:'#bb98fd',blue:'#75d9f3'}[type],true);g.position.set((Math.random()-.5)*16,1.1+Math.random()*3,61+Math.random()*5);}
 memoryNext(){const a=this.active;if(!a||a.kind!=='memory')return;a.round++;a.sequence.push(Math.floor(Math.random()*4));a.index=0;a.showIndex=0;a.phase='show';a.next=Date.now()+600;a.lit=-1;}
 lightPanel(index){const a=this.active;if(!a)return;a.items.forEach((g,i)=>{g.children[0].scale.z=i===index?.9:.4;g.children[0].material.emissiveIntensity=i===index?3:0;});a.lit=index;}
 interact(r){const a=this.active;if(r.action==='event'){this.collectEvent(r.data);return;}if(!a)return;if(r.action==='target'&&a.kind==='target'){const g=a.items[r.data];a.score=Math.max(0,a.score+({blue:1,purple:3,gold:10,red:-3}[g.userData.type]));this.world.burst(g.position,'#b4edff',8);this.retarget(g);this.state.emit('sound',500);}
 if(r.action==='memory'&&a.kind==='memory'&&a.phase==='input'){const i=r.data;this.lightPanel(i);a.unlight=Date.now()+180;this.state.emit('sound',300+i*150);if(i!==a.sequence[a.index]){this.state.s.stats.memory=Math.max(this.state.s.stats.memory,a.round-1);this.finish((a.round-1)*4,`${a.round-1} rounds stabilised.`);return;}a.index++;if(a.index===a.sequence.length){this.state.s.stats.memory=Math.max(this.state.s.stats.memory,a.round);if(a.round===8)this.finish(40,'Perfect stabilisation. All eight rounds completed.');else{a.phase='wait';a.next=Date.now()+600;}}}
 if(r.action==='boss'&&a.kind==='boss'){const damage=(this.state.manual+this.state.cps*.15)*(1+(this.state.fx.bossDamage||0));a.hp-=damage;this.world.burst(a.boss.position,'#f8b7dd',7);this.world.shake=.03;this.state.emit('damage',damage);this.state.emit('sound',140);if(a.hp<=0){this.state.s.stats.bosses++;this.state.q('boss');this.state.s.cores++;this.state.s.coreTotal++;this.state.addPoints(2);this.state.s.dust+=10;this.finish(25,'Boss defeated · +1 quantum core · +2 Skill Points · +10 stardust');}}}
 finish(score,message){const kind=this.active?.kind;if(!kind)return;this.state.s.stats.games++;if(score>0)this.state.s.stats.wins++;this.state.q('game');const tokens=Math.max(0,Math.min(40,Math.floor(score))),energy=Math.max(100,this.state.cps*3)*Math.min(60,score);this.state.s.tokens+=tokens;this.state.gain(energy);this.state.xp(Math.min(250,score*5));this.clear();this.state.progress();this.state.save();this.state.emit('result',{kind,score,tokens,energy,message});}
 spawnEvent(){if(this.event||this.active||this.state.s.lifetime<500)return;const kinds=['surge','storm','meltdown','portal',...(this.state.fx.golden?['golden']:[]),...(this.state.s.rebirths?['invasion']:[])],kind=kinds[Math.floor(Math.random()*kinds.length)];this.event={kind,end:Date.now()+(kind==='invasion'?90000:45000),left:kind==='storm'?5:kind==='invasion'?4:1,hits:0};const w=this.world,a=this.event;let count=a.left;if(kind==='surge'){this.state.addBoost('passive',5,30);a.end=Date.now()+30000;this.state.notice('POWER SURGE · 5× production for 30 seconds');return;}for(let i=0;i<count;i++){const g=new THREE.Group();g.position.set((i-2)*2,1.3,kind==='portal'?-6:4);if(kind==='portal'){w.ring(g,0,0,0,1.2,'#b3a0fc',0);w.sphere(g,0,0,0,.6,'#806eb7',true);}else if(kind==='golden'){w.sphere(g,0,0,0,.4,'#f4d077',true);w.ring(g,0,0,0,.65,'#f4d077');}else{const m=new THREE.Mesh(new THREE.OctahedronGeometry(kind==='invasion'?.65:.3),w.mat(kind==='invasion'?'#ae78ea':'#f1cf8e',true));g.add(m);}w.addTarget(g,'event',i,kind==='meltdown'?'Stabilise the reactor anomaly':kind==='invasion'?'Disrupt void anchor':'Collect '+kind,kind==='golden'?4:3.5);this.eventObjects.push(g);}this.state.notice({storm:'ENERGY STORM · Five crystals appeared in Origin Laboratory',golden:'GOLDEN DRONE · Catch the visitor in Origin Laboratory',meltdown:'REACTOR MELTDOWN · Stabilise the anomaly in Origin Laboratory',portal:'TEMPORAL PORTAL · Find the bonus portal in Origin Laboratory',invasion:'VOID INVASION · Disrupt four anchors in Origin Laboratory'}[kind]);}
 collectEvent(index){const e=this.event;if(!e||e.end<Date.now())return;if(e.kind==='meltdown'){e.hits++;if(e.hits<10){this.state.notice(`Stabilisation ${e.hits}/10`);return;}}const g=this.eventObjects[index];if(!g||!g.visible)return;g.visible=false;e.left--;this.world.burst(g.position,'#f0cf8f',12);if(e.kind==='portal'){this.state.secret('hidden');this.state.addBoost('xp',2,300);}this.state.gain(Math.max(500,this.state.cps*30)*(1+(this.state.fx.rare||0)));if(e.left<=0){this.state.s.stats.events++;this.state.s.dust+=e.kind==='invasion'?20:5;if(e.kind==='invasion')this.state.unlockSkin('void');this.state.notice('World event complete · energy cache and stardust');this.clearEvent();}}
 clearEvent(){this.eventObjects.forEach(o=>this.world.removeTarget(o));this.eventObjects=[];this.event=null;this.world.scene.fog.color.copy(this.world.scene.background);}
 update(dt){const now=Date.now(),a=this.active,w=this.world;if(a){if(now>=a.end){this.finish(a.kind==='target'||a.kind==='catch'?a.score:0,a.kind==='boss'?'The hostile core escaped.':a.kind==='parkour'?'Time expired. Try the course again.':`${a.score} points collected.`);return;}
 if(a.kind==='memory'){if(a.unlight&&now>a.unlight){this.lightPanel(-1);a.unlight=0;}if(now>=a.next){if(a.phase==='show'){if(a.lit>=0){this.lightPanel(-1);a.next=now+200;}else if(a.showIndex<a.sequence.length){this.lightPanel(a.sequence[a.showIndex++]);this.state.emit('sound',300+a.lit*150);a.next=now+550;}else{a.phase='input';a.next=Infinity;}}else if(a.phase==='wait')this.memoryNext();}}
 if(a.kind==='target')a.items.forEach((g,i)=>g.position.y+=Math.sin(w.clock*2+i)*dt*.15);
 if(a.kind==='catch'){a.spawn-=dt;if(a.spawn<=0){a.spawn=.4;const r=Math.random(),value=r<.02?15:r<.1?8:r<.27?5:1,color=value===15?'#ba8bfa':value===8?'#c5f4ff':value===5?'#f2d182':'#7ee8c4';const m=new THREE.Mesh(new THREE.OctahedronGeometry(.3),w.mat(color,true));m.position.set(68+(Math.random()-.5)*16,7,70+(Math.random()-.5)*16);w.scene.add(m);this.objects.push(m);a.items.push({m,value});}a.items=a.items.filter(item=>{item.m.position.y-=dt*3;item.m.rotation.y+=dt;const p=item.m.position;if(p.y<1.5&&Math.hypot(p.x-w.player.x,p.z-w.player.z)<1.4){a.score+=item.value;w.burst(p,'#b0f8d4',5);w.scene.remove(item.m);return false;}if(p.y<0){w.scene.remove(item.m);return false;}return true;});}
 if(a.kind==='parkour'){if(w.player.y>=3.3&&Math.hypot(w.player.x-108,w.player.z-42)<2.7){const seconds=(now-a.start)/1000;this.state.s.stats.parkour=this.state.s.stats.parkour?Math.min(seconds,this.state.s.stats.parkour):seconds;this.finish(Math.max(10,50-Math.floor(seconds/2)),`Course completed in ${seconds.toFixed(1)}s · ${a.falls} falls`);return;}const p=w.parkourPlatforms[5];if(Math.abs(w.player.y-p.y)<.1&&Math.abs(w.player.x-p.x)<p.w/2&&Math.abs(w.player.z-p.z)<p.d/2){p.stood=(p.stood||0)+dt;if(p.stood>1){p.disabled=true;p.mesh.visible=false;}}for(let i=0;i<3;i++){const bx=108,bz=65-i*8,angle=w.clock*.9+i,dx=w.player.x-bx,dz=w.player.z-bz,along=dx*Math.cos(angle)-dz*Math.sin(angle),across=dx*Math.sin(angle)+dz*Math.cos(angle);if(Math.abs(across)<.24&&Math.abs(along)<3.5&&Math.abs(w.player.y+.8-(1.6+i*.9))<.65&&now>(a.hazardCooldown||0)){a.hazardCooldown=now+1500;a.end-=3000;w.shake=.06;this.state.notice('Laser contact · −3 seconds');}}}
 if(a.kind==='boss'){a.boss.rotation.y+=dt*.4;a.boss.children.forEach((o,i)=>{if(i)o.rotation.z+=dt*(.2+i*.2);});a.beam.rotation.y=w.clock*.8;const dx=w.player.x+34,dz=w.player.z-70,across=dx*Math.sin(w.clock*.8)+dz*Math.cos(w.clock*.8);if(Math.abs(across)<.25&&w.player.y<.6&&now>(a.lastHit||0)+1800){a.lastHit=now;a.end-=2000;w.shake=.08;this.state.notice('Beam contact · −2 seconds. Jump over the sweep.');}}}
 if(now>this.nextEvent){this.spawnEvent();this.nextEvent=now+(90000+Math.random()*60000)/(1+(this.state.fx.rare||0)*.2);}if(this.event){if(now>this.event.end){if(this.event.kind!=='surge')this.state.notice('The world event faded.');this.clearEvent();}else{this.eventObjects.forEach((g,i)=>{g.rotation.y+=dt*.5;if(this.event.kind==='golden'){g.position.x=Math.sin(w.clock*.5)*6;g.position.z=4+Math.cos(w.clock*.5)*2;}});if(this.event.kind==='invasion')w.scene.fog.color.set('#251233');}}
 }
}
