/* Generated audio is local and opt-in. Effects use stereo position relative to the camera. */
export class AudioSystem{
 constructor(state,world){this.state=state;this.world=world;this.ctx=null;this.musicNodes=[];this.lastTheme='';this.lastHum=0;state.on((type,data)=>{if(type==='pulse')this.tone(data.critical?620:210,.12,this.pan(0,-1.5));if(type==='sound')this.tone(data,.14);if(type==='skill')this.tone(780,.22);if(type==='machine')this.tone(390,.16);if(type==='level')this.tone(900,.2);if(type==='area')this.tone(280,.4);if(type==='audio-settings')this.music(true);});}
 init(){try{this.ctx??=new (window.AudioContext||window.webkitAudioContext)();if(this.ctx.state==='suspended')this.ctx.resume();return true;}catch{return false;}}
 pan(x,z){const dx=x-this.world.player.x,dz=z-this.world.player.z;return Math.max(-1,Math.min(1,(dx*Math.cos(this.world.yaw)-dz*Math.sin(this.world.yaw))/8));}
 tone(frequency=300,length=.13,pan=0){const s=this.state.s.settings;if(!s.sound||!s.master||!this.init())return;const o=this.ctx.createOscillator(),g=this.ctx.createGain(),p=this.ctx.createStereoPanner();o.type='sine';o.frequency.setValueAtTime(frequency,this.ctx.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(30,frequency*.55),this.ctx.currentTime+length);g.gain.setValueAtTime(Math.max(.001,s.master*s.sfx*.13),this.ctx.currentTime);g.gain.exponentialRampToValueAtTime(.0001,this.ctx.currentTime+length);p.pan.value=pan;o.connect(g).connect(p).connect(this.ctx.destination);o.start();o.stop(this.ctx.currentTime+length+.02);o.onended=()=>{o.disconnect();g.disconnect();p.disconnect();};}
 music(force=false){const s=this.state.s.settings,theme=this.world.arena==='boss'?'boss':this.world.zone;if(!force&&this.lastTheme===theme)return;this.lastTheme=theme;this.musicNodes.forEach(o=>{try{o.stop();o.disconnect();}catch{}});this.musicNodes=[];if(!s.music||!s.master||!this.init())return;const notes=theme==='boss'?[65.4,77.78,98]:['dimension','quantum','deep'].includes(theme)?[110,130.81,164.81]:theme==='factory'?[98,123.47,146.83]:[130.81,164.81,196];this.musicNodes=notes.map((freq,i)=>{const o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type='sine';o.frequency.value=freq;g.gain.value=s.master*s.musicVolume*.028;o.connect(g).connect(this.ctx.destination);o.start();return o;});}
 update(dt){this.music();this.lastHum+=dt;if(this.lastHum>4){this.lastHum=0;if(this.state.s.settings.sound&&this.state.s.settings.music&&this.world.player.distanceTo({x:0,y:0,z:-1.5})<10)this.tone(75,.4,this.pan(0,-1.5));}}
}
