export const VERSION=2, SAVE_KEY='nova-foundry-3d-v2', LIMIT=1e280;
export const BRANCHES=[['power','Power','#6ad9ff','Manual energy and reactor control'],['auto','Automation','#77edbd','Machines, workers and passive income'],['luck','Fortune','#f4ce78','Critical energy and rare signals'],['offline','Offline','#aaa3ff','Storage and away-time production'],['rebirth','Rebirth','#f799c9','Faster, stronger new beginnings'],['explore','Exploration','#ffac79','Rooms, research and new worlds']];
const names=[
 ['Stronger pulse','Compression','Critical energy','Combo capacitor','Overcharged interaction','Critical mastery','Focused beam','Core resonance','Critical overload','Nuclear fingers','Plasma feedback','Hyperactive core','GOD TOUCH','Solar hands','Pulse echo','Reactor mastery'],
 ['Basic automation','Faster generators','Improved machinery','Robot workers','AI management','Self-improving machines','Assembly line','Precision bearings','Autonomous empire','Machine empire','Quantum timing','Distributed network','FULL AUTOMATION','Machine learning','Clean energy','Industrial mastery'],
 ['Lucky energy','Better criticals','Lucky generator','Golden signal','Jackpot energy','Fortune master','Stardust pockets','Lucky research','Impossible luck','Crystal magnet','Rare circuitry','Double salvage','GOLDEN UNIVERSE','Probability wave','Fortunate pulse','Fortune mastery'],
 ['Offline production','Better storage','Efficient shutdown','Backup cells','Extended storage','Sleep mode','Coolant reserve','Battery farm','Eternal production','Deep sleep','Hibernate','Long-term archive','NEVER OFFLINE','Chrono vault','Time crystal','Storage mastery'],
 ['Rebirth knowledge','Permanent energy','Faster recovery','Core affinity','Rebirth memory','Eternal skill','Quantum rhythm','Rapid reboot','Rebirth master','Ancestral spark','Machine memory','Clean restart','IMMORTAL CORE','Quantum yield','Core scientist','Prestige mastery'],
 ['Facility expansion','Survey scanner','Research access','Factory logistics','Deep facility','Quantum access','Launch technology','Wayfinding','Orbital engineering','Planetary survey','Dimensional research','Fast travel network','MULTIVERSE ACCESS','Explorer insight','Research network','Frontier mastery']
];
const special={
 'power:0':['+10% manual energy per level.',{click:.1}], 'power:1':['+25% manual energy.',{click:.25}], 'power:3':['Maximum combo +1×.',{combo:1}], 'auto:1':['+15% passive income.',{passive:.15}], 'auto:2':['+25% passive income.',{passive:.25}], 'auto:4':['+50% passive income.',{passive:.5}], 'luck:0':['+2% critical chance.',{crit:.02}], 'luck:1':['Critical multiplier +5×.',{critMult:5}], 'rebirth:8':['+100% quantum yield.',{prestige:1}], 'explore:1':['Shows uncollected energy shards on the minimap.',{scanner:1}],
 'power:2':['Critical interactions unlocked at 5% chance.',{critUnlock:1}], 'power:4':['Every tenth interaction earns 5× energy.',{tenth:1}], 'power:5':['+10% critical chance.',{crit:.1}], 'power:8':['Critical multiplier +5×.',{critMult:5}], 'power:9':['Manual energy +500%.',{click:5}], 'power:11':['Manual energy ×10, passive energy ×0.5.',{manualKeystone:1}], 'power:12':['Manual energy ×8.',{god:1}],
 'auto:0':['Unlocks machine production and construction.',{automation:1}], 'auto:3':['Robot workers join the facility; +2 automatic pulses/sec.',{workers:1,autoClicks:2}], 'auto:5':['Passive income grows +1% per active minute, up to +100%.',{selfImprove:1}], 'auto:9':['Passive energy ×5, manual energy ×0.2.',{machineKeystone:1}], 'auto:12':['Passive production ×8.',{fullAuto:1}],
 'luck:2':['Machines have a 5% chance each second to produce a bonus tick.',{luckyMachine:1}], 'luck:3':['Golden drones can visit your facility.',{golden:1}], 'luck:4':['Each manual pulse has a 0.2% chance of a 100× jackpot.',{jackpot:1}], 'luck:8':['Rare event rewards ×2.',{rare:1}], 'luck:9':['World shards can be collected from farther away.',{magnet:1}], 'luck:12':['Critical chance +15%; event rewards ×2.',{crit:.15,rare:1}],
 'offline:0':['Unlock offline earnings at 25% efficiency.',{offline:.25}], 'offline:1':['Offline storage +4 hours.',{hours:4}], 'offline:2':['Offline efficiency +25%.',{offline:.25}], 'offline:4':['Offline storage +12 hours.',{hours:12}], 'offline:5':['Offline efficiency +25%.',{offline:.25}], 'offline:8':['Offline storage +24 hours (48h maximum).',{hours:24}], 'offline:12':['Offline efficiency becomes 100%.',{neverOffline:1}],
 'rebirth:1':['Each rebirth starts with 500 extra energy.',{startEnergy:500}], 'rebirth:4':['Keep 10% of each machine level through rebirth.',{memory:.1}], 'rebirth:5':['Earn 3 extra Skill Points each rebirth.',{rebirthPoints:3}], 'rebirth:10':['Start with one extra collector per rebirth.',{startMachine:1}], 'rebirth:12':['Quantum core passive bonus doubles.',{immortal:1}],
 'explore:0':['Allows the Generator Hall to open at 250 run energy.',{access:1}], 'explore:2':['Allows the Research Wing to open at 3K run energy.',{research:1}], 'explore:3':['Allows the Factory to open at 1.5K run energy.',{factory:1}], 'explore:4':['Allows the Deep Facility to open at 10K run energy.',{deep:1}], 'explore:5':['Allows the Quantum Chamber to open at 25K run energy.',{quantum:1}], 'explore:6':['Allows the Launch Platform to open at 100K run energy.',{launch:1}], 'explore:8':['Allows the Orbital Station to open at 1M run energy.',{orbital:1}], 'explore:9':['Allows the Alien Outpost to open at 10M run energy.',{planet:1}], 'explore:10':['Allows the Dimensional Realm to open at 100M run energy.',{dimension:1}], 'explore:11':['Unlock fast travel to all discovered areas.',{fastTravel:1}], 'explore:12':['New Reality becomes available after BREAK REALITY.',{multiverse:1}]
};
export const NODES=[];
const layout=[[1,0],[0,1],[1,1],[2,1],[0,2],[1,2],[2,2],[3,2],[0,3],[1,3],[2,3],[3,3],[1,4],[0,5],[1,5],[2,5]];
const parents=[[],[0],[0],[0],[1],[2],[2],[3],[4],[5],[6],[7],[8,9,10],[12],[12],[12]];
BRANCHES.forEach((b,bi)=>names[bi].forEach((name,i)=>{let effects,desc;const spec=special[b[0]+':'+i];if(spec){[desc,effects]=spec;}else{const key=['click','passive','crit','offlineProduction','prestige','xp'][bi],amount=key==='crit'?.015:i>12?.3:.15;effects={[key]:amount};desc=`+${Math.round(amount*100)}% ${['manual energy','passive income','critical chance','offline-only production','quantum yield','XP gain'][bi]} per level.`;}
NODES.push({id:`${b[0]}-${i}`,name,desc,branch:b[0],tree:'main',color:b[2],x:bi*350+layout[i][0]*76+36,y:140+layout[i][1]*158,max:bi===0&&i===0?10:spec?1:5,cost:i===12?10:i>=8?3:i>=4?2:1,requires:parents[i].map(p=>`${b[0]}-${p}`),effects,keystone:[11,12].includes(i)});}));
const cross=[['Quantum automation',['auto-4','power-5'],{luckyMachine:1,passive:.5},'Machine bonus ticks unlocked and +50% passive energy.'],['Eternal reactor',['offline-8','rebirth-12'],{memory:.2},'Keep an additional 20% of machine levels after rebirth.'],['Explorer drones',['auto-3','explore-4'],{dronePower:1},'Equipped drone bonuses double.'],['Sleeping giant',['offline-5','power-9'],{offlineProduction:1},'Offline-only production +100%.'],['Fortunate rebirth',['luck-8','rebirth-8'],{prestige:1},'Quantum yield +100%.'],['Dimensional network',['explore-10','auto-12'],{global:2},'All energy +200%.']];
cross.forEach((d,i)=>NODES.push({id:'cross-'+i,name:d[0],requires:d[1],effects:d[2],desc:d[3],tree:'main',branch:'cross',color:'#dce7ff',x:110+i*335,y:1220,max:1,cost:8,keystone:true}));
const quantum=[['Permanent production',{global:.1},'+10% all energy per level.'],['Faster beginning',{startEnergy:10000},'+10K starting energy per level.'],['Core memory',{startMachine:1},'+1 starting collector per level.'],['Quantum knowledge',{rebirthPoints:1},'+1 Skill Point per rebirth per level.'],['Rebirth efficiency',{prestige:.15},'+15% quantum yield per level.'],['Permanent criticals',{crit:.01},'+1% critical chance per level.'],['Machine memory',{memory:.02},'Keep +2% machine levels per level.'],['Quantum cooling',{click:.25},'+25% manual energy per level.'],['Stellar factory',{passive:.25},'+25% passive energy per level.'],['Timeless network',{hours:2},'+2h offline capacity per level, up to 48h.'],['Ancestral fortune',{rare:.1},'+10% rare event rewards per level.'],['Quantum architect',{global:.5},'+50% all energy per level.']];
quantum.forEach((d,i)=>NODES.push({id:'q-'+i,name:d[0],effects:d[1],desc:d[2],tree:'quantum',branch:'quantum',color:'#f4ce78',x:180+(i%3)*220,y:130+Math.floor(i/3)*170,max:100,cost:1+Math.floor(i/3),requires:i<3?[]:['q-'+(i-3)],keystone:i>=9}));
const asc=[['Infinite energy',{global:2},'+200% all energy.'],['Rebirth memory+',{memory:.2},'Keep +20% of machine levels.'],['Dimensional production',{dimensionProduction:1},'+100% passive income per ascension.'],['Temporal automation',{temporal:1},'Production continues during rebirth animations.'],['Infinite knowledge',{levelPoints:1},'+1 additional Skill Point on future level-ups.'],['Reality armour',{bossDamage:2},'+200% boss damage.'],['Infinite storage',{neverOffline:1},'100% offline efficiency.'],['BREAK REALITY',{breakReality:1},'Unlock New Reality at 3 ascensions with Multiverse Access.']];
asc.forEach((d,i)=>NODES.push({id:'a-'+i,name:d[0],effects:d[1],desc:d[2],tree:'ascension',branch:'ascension',color:'#c0a1ff',x:220+(i%2)*260,y:130+Math.floor(i/2)*180,max:1,cost:i===7?3:1,requires:i<2?[]:['a-'+(i-2)],keystone:i===7}));
BRANCHES.forEach((b,i)=>[0,1].forEach(t=>NODES.push({id:`m-${i}-${t}`,name:b[1]+(t?' transcendence':' mastery'),desc:`+${t?40:20}% ${['manual energy','passive income','rare rewards','offline-only production','quantum yield','XP'][i]} per level. Unlimited research; costs increase each level.`,effects:{[['click','passive','rare','offlineProduction','prestige','xp'][i]]:t?.4:.2},tree:'mastery',branch:b[0],color:b[2],x:110+i*180,y:180+t*230,max:1000000,cost:t?5:3,requires:t?[`m-${i}-0`]:[],keystone:!!t})));
export const NODE_MAP=Object.fromEntries(NODES.map(n=>[n.id,n]));
export const AREAS=[
{id:'lab',name:'Origin Laboratory',x:0,z:0,need:0,flag:null,color:'#72d8ee',subtitle:'Where a universe begins.'},
{id:'generator',name:'Generator Hall',x:28,z:0,need:250,flag:'access',color:'#78edbc',subtitle:'The first step toward independence.'},
{id:'factory',name:'Robot Factory',x:56,z:0,need:1500,flag:'factory',color:'#f4c67b',subtitle:'An empire in motion.'},
{id:'research',name:'Research Wing',x:28,z:-28,need:3000,flag:'research',color:'#a79df8',subtitle:'Curiosity becomes power.'},
{id:'quantum',name:'Quantum Chamber',x:56,z:-28,need:25000,flag:'quantum',color:'#f49fcb',subtitle:'Beyond ordinary physics.'},
{id:'deep',name:'Deep Facility',x:0,z:-28,need:10000,flag:'deep',color:'#67d7bf',subtitle:'Forgotten infrastructure. New possibilities.'},
{id:'launch',name:'Launch Platform',x:-28,z:0,need:100000,flag:'launch',color:'#efb086',subtitle:'Your world is getting smaller.'},
{id:'orbital',name:'Orbital Station',x:-56,z:0,need:1e6,flag:'orbital',color:'#9ccdfc',subtitle:'A foundry among the stars.'},
{id:'planet',name:'Alien Outpost',x:-56,z:-28,need:1e7,flag:'planet',color:'#aeed9c',subtitle:'A different sun. The same ambition.'},
{id:'dimension',name:'Dimensional Realm',x:-28,z:-28,need:1e8,flag:'dimension',color:'#dc99ff',subtitle:'The edge of what is possible.'}];
export const MACHINES=[
['collector','Energy collector','lab',20,1.15,1],['generator','Ion generator','generator',150,1.16,9],['fusion','Fusion engine','factory',1800,1.17,110],['research','Photon processor','research',12000,1.18,800],['deep','Dark matter drill','deep',65000,1.19,4500],['quantum','Quantum reactor','quantum',3e5,1.2,24000],['launch','Stellar turbine','launch',2e6,1.2,170000],['orbital','Dyson relay','orbital',2e7,1.21,1.8e6],['planet','Planetary engine','planet',3e8,1.22,3e7],['dimension','Dimensional engine','dimension',5e9,1.23,5e8]
].map((d,i)=>({id:d[0],name:d[1],area:d[2],base:d[3],growth:d[4],rate:d[5],i}));
export const SKINS=[['azure','Origin blue','#72d8ee','Common',0],['inferno','Inferno','#ff8658','Rare',20],['frozen','Frozen star','#c0f1ff','Rare',20],['toxic','Toxic glow','#a1ff72','Uncommon',12],['gold','Golden core','#ffd16b','Epic',35],['void','Void heart','#ae78fb','Legendary',60],['galaxy','Galaxy','#ff9ee2','Epic',40],['blackhole','Black hole','#7363c5','Mythic',80],['developer','Developer signal','#ddfc8b','Secret',-1],['reality','Reality core','#ffffff','Mythic',-1]];
export const OUTFITS=['Scientist','Engineer','Robot','Hazmat','Space suit','Quantum armour','Void armour','Golden armour'];
export const DRONES=[['Maintenance drone','+5% passive income','#7decc0',20],['Lucky drone','+2% critical chance','#f7d477',25],['Mining drone','Periodic energy deliveries','#72d9f9',30],['Quantum drone','+10% quantum yield','#e49dd7',40],['Void drone','+8% all energy','#bd8aff',60]];
export const FACILITY=[['Cooling system','+10% manual energy','click'],['Power grid','+10% passive energy','passive'],['Network system','+1 automatic pulse/sec','autoClicks'],['Storage system','+1h offline capacity (48h maximum)','hours'],['Research network','+10% XP gain','xp']];
export const RESEARCH=[['Energy compression','+25% manual energy',1500,30,'click'],['Robot intelligence','+25% passive energy',7500,60,'passive'],['Quantum physics','+25% quantum yield',50000,90,'prestige'],['Advanced materials','+25% all energy',250000,120,'global'],['Dimensional science','+25% XP gain',1e6,180,'xp']];
export const NPC_QUESTS=[['engineer','Chief engineer','Generate 100K lifetime energy','lifetime',100000],['scientist','Dr. Lyra','Unlock 12 skill nodes','nodes',12],['technician','Technician Omi','Own 25 machine levels','machines',25],['explorer','Explorer Vega','Discover 6 facility areas','areas',6]];
export const BOSSES=['Corrupted Core','Rogue AI','Quantum Guardian','Void Machine','Planet Eater','Dimensional Titan','Reality Breaker'];
