import * as THREE from 'three';
import {World} from './world.js';
import {UI} from './ui.js';
import {State,timeLabel} from './state.js';
import {MACHINES,RESEARCH,SKINS,LIMIT} from './data.js';

const $=id=>document.getElementById(id);
const accents={overview:'#95bdcf',bank:'#d7b66d',tree:'#73acfa',workers:'#e2a270',research:'#b69bed',rebirth:'#dc89bc',arcade:'#68d6db',collection:'#bda3df',storage:'#d9c179',market:'#81c5a1',factory:'#91b8c6'};
const names={overview:'Headquarters',bank:'Treasury',tree:'Upgrade lab',workers:'Worker office',research:'Research centre',rebirth:'Rebirth shrine',arcade:'Arcade',collection:'Cosmetic showroom',storage:'Storage warehouse',market:'Marketplace',factory:'Production floor'};
const icon=(kind='box')=>`<svg class="ui-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${({box:'<path d="m12 3 9 5v9l-9 5-9-5V8l9-5Zm0 9v10M3 8l9 4 9-4M7 5.8l9 5V16"/>',staff:'<circle cx="12" cy="8" r="4"/><path d="M4 21v-3a8 8 0 0 1 16 0v3"/>',gear:'<circle cx="12" cy="12" r="4"/><path d="M12 2v3m0 14v3M2 12h3m14 0h3M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2"/>',chart:'<path d="M3 3v18h18M7 16l4-5 4 2 6-8"/>',bolt:'<path d="m14 2-9 12h6l-1 8 9-13h-6l1-7Z"/>',play:'<rect x="2" y="5" width="20" height="15" rx="4"/><path d="M6 12h6m-3-3v6m7-4h1m2 3h1"/>'})[kind]||'<path d="M4 12h16M12 4v16"/>'}</svg>`;
const btn=(label,action,attrs='',disabled=false)=>`<button data-action="${action}" ${attrs} ${disabled?'disabled':''}>${label}</button>`;
const fresh=()=>({stock:[0,0,0,0],workers:[],layout:{},decor:[],prefs:{scale:1,rotation:1,notifications:true},tutorial:0});
const data=state=>state.s.management??=(fresh());
const materials=[['Iron','Common',8,'#9bafc1'],['Gold','Uncommon',35,'#d9bd6f'],['Components','Rare',110,'#88c5bb'],['Rare core','Epic',650,'#b7a1e4']];
const price=i=>materials[i][2]*(1+.12*Math.sin(Math.floor(Date.now()/15000)*.63+i*2));
const stat=(label,value)=>`<div class="metric"><span>${label}</span><strong>${value}</strong></div>`;

// Optional extension keeps existing v2 saves readable and validates imported additions.
const validate=State.prototype.validate;
State.prototype.validate=function(raw){const s=validate.call(this,raw),m=raw.management;if(!m)return s;const out=fresh();const number=(v,max)=>Number.isFinite(v)&&v>=0&&v<=max;
 if(Array.isArray(m.stock)&&m.stock.length===4)out.stock=m.stock.map(v=>number(v,10000)?v:0);
 if(Array.isArray(m.workers))out.workers=m.workers.slice(0,6).filter(w=>Number.isInteger(w.id)&&w.id>=0&&w.id<6&&Number.isInteger(w.level)&&w.level>=1&&w.level<=20&&Number.isInteger(w.machine)&&w.machine>=-1&&w.machine<MACHINES.length).map(w=>({id:w.id,level:w.level,machine:w.machine}));
 out.workers=out.workers.filter((w,i,a)=>a.findIndex(x=>x.id===w.id)===i);
 for(const [key,p]of Object.entries(m.layout||{}))if(Object.keys(names).includes(key)&&Array.isArray(p)&&p.length===2&&p.every(v=>Number.isFinite(v)&&Math.abs(v)<=18))out.layout[key]=p;
 if(Array.isArray(m.decor))out.decor=m.decor.slice(0,50).filter(p=>['road','light','planter'].includes(p.type)&&Number.isFinite(p.x)&&Math.abs(p.x)<=18&&Number.isFinite(p.z)&&Math.abs(p.z)<=18);
 out.prefs={scale:[.85,1,1.15].includes(m.prefs?.scale)?m.prefs.scale:1,rotation:[.5,1,1.5].includes(m.prefs?.rotation)?m.prefs.rotation:1,notifications:m.prefs?.notifications!==false};out.tutorial=number(m.tutorial,3)?Math.floor(m.tutorial):0;s.management=out;return s;
};
const tick=State.prototype.tick;
State.prototype.tick=function(dt){tick.call(this,dt);const m=data(this),total=this.s.machines.reduce((a,b)=>a+b,0),space=Math.max(0,10000-m.stock.reduce((a,b)=>a+b,0));let remaining=space;
 if(this.fx.automation&&this.s.challenge?.id!=='manual')for(let i=0;i<4;i++){const amount=Math.min(remaining,total*dt*[.12,.025,.006,.0004][i]);m.stock[i]+=amount;remaining-=amount;}
};
const cps=Object.getOwnPropertyDescriptor(State.prototype,'cps').get;
Object.defineProperty(State.prototype,'cps',{get(){const bonus=this.fx.automation&&this.s.challenge?.id!=='manual'?data(this).workers.reduce((n,w)=>n+(w.machine>=0?this.machineRate(w.machine)*w.level*.05:0),0):0;return Math.min(LIMIT,cps.call(this)+bonus);}});
for(const method of ['performRebirth','ascend','newReality']){const original=State.prototype[method];State.prototype[method]=function(...args){const m=data(this),before=this.s.rebirths+this.s.ascensions+this.s.reality;const result=original.apply(this,args);if(this.s.rebirths+this.s.ascensions+this.s.reality!==before){this.s.management={...fresh(),prefs:m.prefs,tutorial:3};this.emit('world');this.save();}return result;};}

const originalMat=World.prototype.mat;
World.prototype.mat=function(color,glow=false){const palette={'#8db471':'#31464b','#97ba77':'#31464b','#b9c59e':'#25353d','#d7bc86':'#4b565c','#b2bc91':'#2e3d45','#bd9462':'#586976','#caab7c':'#4a5c64','#d7c797':'#44575e','#aaa98d':'#485965','#ece2c5':'#8dabb5','#a7a38a':'#3d505b','#d0c5a3':'#687d84','#b3986c':'#607681','#58884e':'#3c635c','#69974f':'#416b61','#73a358':'#4a7566','#96714d':'#48514e','#aa865c':'#425354','#b8cd91':'#26383c'};return originalMat.call(this,palette[color]||color,glow);};
World.prototype.house=function(parent,x,z,title,action,color,w=4.5,d=3.6){const g=new THREE.Group();g.position.set(x,0,z);parent.add(g);const c=accents[action]||'#88aeba';
 this.box(g,0,.12,0,w+.6,.24,d+.6,'#263540');this.box(g,0,1,0,w,1.8,d,'#536675');this.box(g,0,2,0,w+.2,.2,d+.2,'#25343f');this.box(g,0,2.14,d/2,w,.07,.08,c,true);
 for(const wx of [-1,0,1])this.box(g,wx*w*.27,1.15,d/2+.02,.55,.58,.05,c,true);
 this.box(g,0,.48,d/2+.12,.65,.95,.1,'#243640');
 if(action==='rebirth'){this.cylinder(g,0,2.6,0,1,.8,'#55465f');this.ring(g,0,3.4,0,1.2,c,0);this.sphere(g,0,3.4,0,.45,c,true);}
 else if(['research','tree'].includes(action)){this.cylinder(g,0,2.25,0,1,.4,'#859aaa');this.sphere(g,0,2.8,0,.8,c,true);this.ring(g,0,2.8,0,1,c,0);}
 else if(action==='bank'){for(const px of [-1.5,-.75,.75,1.5])this.box(g,px,1,d/2+.2,.15,1.8,.22,'#adac94');this.box(g,0,2.4,0,w*.7,.65,d*.6,'#3f5361');}
 else if(action==='storage'){for(const px of [-1.3,0,1.3])this.box(g,px,2.3,0,.9,.5,d*.65,'#6b7880');}
 else if(action==='workers'){this.box(g,-.8,2.45,0,w*.5,.7,d*.7,'#6b7e8a');this.box(g,-.8,2.5,d*.36,w*.45,.14,.06,c,true);}
 else if(action==='arcade'){for(let i=0;i<3;i++)this.box(g,-1+i,2.4,0,.45,.6,.45,[c,'#b194df','#80bbce'][i],true);}
 else {this.box(g,-.8,2.3,-.4,1.1,.4,1.1,'#728895');this.box(g,1,2.5,-.5,.2,.9,.2,c,true);}
 g.userData.facility=action;g.userData.label=names[action]||title;this.bind(g,action,null,g.userData.label);return g;
};
World.prototype.buildManagement=function(){this.facilities={};this.scene.traverse(g=>{if(g.userData.facility&&!this.facilities[g.userData.facility])this.facilities[g.userData.facility]=g;});const lab=this.areaGroups.lab;
 this.box(lab,0,-.23,0,36,.2,36,'#293d45');this.box(lab,0,.005,0,36,.03,2.5,'#4b565c');this.box(lab,0,.006,0,2.5,.03,36,'#4b565c');
 const entries=[[-6,-13,'overview'],[6,-13,'bank'],[-14,-5,'workers'],[-14,5,'storage'],[-6,13,'market'],[6,13,'collection'],[14,5,'rebirth'],[14,-5,'research']];
 for(const [x,z,key]of entries){this.box(lab,x,-.18,z,6,.3,6,'#31464b');this.facilities[key]=this.house(lab,x,z,names[key],key,accents[key],4.2,3.5);this.box(lab,x,.02,z>0?z-3:z+3,1.4,.06,3,'#4b565c');}
 this.facilities.tree=this.interactables.find(g=>g.userData.facility==='tree');
 for(const [x,z]of [[-10,-12],[10,-12],[-10,12],[10,12],[-14,0],[14,0]]){this.cylinder(lab,x,1,z,.06,2,'#667985');this.sphere(lab,x,2,z,.16,'#e7ca90',true);}
 this.selection=new THREE.Mesh(new THREE.RingGeometry(2.65,2.72,64),new THREE.MeshBasicMaterial({color:'#8ab9d7',transparent:true,opacity:.7,side:THREE.DoubleSide,depthWrite:false}));this.selection.rotation.x=-Math.PI/2;this.selection.visible=false;this.scene.add(this.selection);this.decorationRoot=new THREE.Group();lab.add(this.decorationRoot);
 this.statusMarkers={};for(const [key,text]of [['tree','↑'],['storage','!'],['research','✓']]){const g=this.facilities[key];this.statusMarkers[key]=this.label(g,text,0,4,0,.8);}
 this.outlines=[];for(const g of Object.values(this.facilities)){const edges=new THREE.LineSegments(new THREE.EdgesGeometry(new THREE.BoxGeometry(4.35,2.2,3.65)),new THREE.LineBasicMaterial({color:accents[g.userData.facility]||'#91bacb',transparent:true,opacity:.35}));edges.position.y=1.15;edges.visible=false;g.add(edges);this.outlines.push({g,edges});}
 this.state.on((type,message)=>{if(type==='world')this.syncLayout();if(type==='notice'&&message.startsWith('Research complete'))this.researchReady=true;});this.syncLayout();
};
World.prototype.syncLayout=function(){for(const [key,g]of Object.entries(this.facilities)){g.userData.original??=[g.position.x,g.position.z];const p=data(this.state).layout[key]||g.userData.original;g.position.set(p[0],0,p[1]);}this.decorationRoot.clear();for(const p of data(this.state).decor){if(p.type==='road')this.box(this.decorationRoot,p.x,.05,p.z,2,.08,2,'#4b565c');else if(p.type==='light'){this.cylinder(this.decorationRoot,p.x,1,p.z,.07,2,'#667985');this.sphere(this.decorationRoot,p.x,2,p.z,.15,'#e7ca90',true);}else this.flowerbed(this.decorationRoot,p.x,p.z,1.6,1.6);}this.renderer.shadowMap.needsUpdate=true;};
World.prototype.focusBuilding=function(r){this.selectedBuilding=r;const p=r.obj.getWorldPosition(new THREE.Vector3());this.goal.copy(p);this.goalSize=Math.max(24,this.goalSize*.88);this.selection.position.set(p.x,.15,p.z);this.selection.material.color.set(accents[r.action]||'#8ab9d7');this.selection.visible=true;};
World.prototype.updateManagement=function(dt){if(this.selection.visible)this.selection.scale.setScalar(this.state.s.settings.reduced?1:1+Math.sin(this.clock*2)*.025);this.statusMarkers.tree.visible=this.state.s.points>0;this.statusMarkers.storage.visible=data(this.state).stock.reduce((a,b)=>a+b,0)>=9999;this.statusMarkers.research.visible=!!this.researchReady;for(const {g,edges}of this.outlines){const selected=this.selectedBuilding?.obj===g;edges.visible=this.current?.obj===g||selected;edges.material.opacity=selected?.7:.25;}this.hoverRing.material.opacity=.38;
 if(this.current&&this.current.obj.userData.facility){this.hoverRing.scale.setScalar(2);}
 this.productionClock=(this.productionClock||0)+dt;if(this.productionClock>5){this.productionClock=0;const g=this.machineGroups.find(g=>g.userData.level>0);if(g&&!this.paused&&this.state.cps>0){const p=g.getWorldPosition(new THREE.Vector3());p.y+=3;p.project(this.camera);if(Math.abs(p.x)<1&&Math.abs(p.y)<1){const el=document.createElement('div');el.className='floater production-floater';el.textContent='+'+this.state.fmt(this.state.cps*5);el.style.left=(p.x*.5+.5)*innerWidth+'px';el.style.top=(-p.y*.5+.5)*innerHeight+'px';$('floaters').append(el);setTimeout(()=>el.remove(),1100);}}}
};

const open=UI.prototype.open,close=UI.prototype.close,render=UI.prototype.render,action=UI.prototype.action,update=UI.prototype.update,interact=UI.prototype.interact,notice=UI.prototype.notice;
UI.prototype.nav=function(){$('menuNav').innerHTML='';};
UI.prototype.open=function(page='overview'){if(this.buildMode)this.stopBuild();if(this.previewSkin)this.restorePreview();const g=this.world.facilities[page];if(g)this.world.focusBuilding({obj:g,action:page});if(page==='research')this.world.researchReady=false;if(!this.opened)this.returnFocus=document.activeElement;open.call(this,page);$('menu').dataset.page=page;$('menu').style.setProperty('--building',accents[page]||'#95bdcf');$('menuTitle').textContent=names[page]||$('menuTitle').textContent;$('menu').setAttribute('role','dialog');$('menu').setAttribute('aria-modal','true');$('menu').setAttribute('aria-labelledby','menuTitle');$('menu').querySelector('.close-button').focus();};
UI.prototype.render=function(){render.call(this);$('menuTitle').textContent=names[this.page]||$('menuTitle').textContent;document.querySelectorAll('#menuContent .icon').forEach(el=>el.innerHTML=icon(this.page==='arcade'?'play':'box'));};
UI.prototype.drawMap=function(){};
UI.prototype.close=function(){this.restorePreview();close.call(this);this.world.selection.visible=false;this.world.selectedBuilding=null;this.returnFocus?.focus?.();};
UI.prototype.closeDialog=function(){$('dialog').close();this.machineIndex=null;this.world.paused=this.opened||!this.started;if(!this.opened){this.world.selection.visible=false;this.world.selectedBuilding=null;}};
UI.prototype.notice=function(message){if(data(this.state).prefs.notifications)notice.call(this,message);};
UI.prototype.interact=function(r){if(this.buildMode){if(r.obj.userData.facility){this.moveBuilding=r.obj;this.notice('Click an open space in the central district to place '+r.label+'.');}return;}
 if(r.obj.userData.facility||r.action==='machine')this.world.focusBuilding(r);
 if(r.action==='machine'){this.machineIndex=r.data;this.open('factory');return;}
 return interact.call(this,r);
};
UI.prototype.overviewView=function(){const s=this.state.s;return `<div class="hq-hero"><div><div class="eyebrow">DISTRICT 01 / OPERATIONS</div><h2>Everything starts<br>with a spark.</h2><p>Your facility is online. Choose a building in the world to manage its operation.</p></div><div class="hq-level"><strong>${this.state.level}</strong><span>FACILITY LEVEL</span></div></div><div class="metrics">${stat('Stored energy',this.state.fmt(s.energy))}${stat('Production / sec',this.state.fmt(this.state.cps))}${stat('Machines online',s.machines.filter(n=>n>0).length)}${stat('Staff',data(this.state).workers.length)}${stat('Rebirths',s.rebirths)}${stat('Time on shift',timeLabel(s.stats.time))}</div><div class="section-title">District planning</div><div class="toolbar">${btn('Arrange buildings','buildmode')}${btn('Expand district','open','data-page="travel"')}${btn('Assignments','open','data-page="missions"')}${btn('Achievements · '+s.achievements.length,'open','data-page="achievements"')}${btn('Lifetime records','open','data-page="stats"')}${btn('Companion drones','open','data-page="drones"')}${btn('Challenge chamber','open','data-page="challenges"',s.rebirths<1)}${btn('Daily supplies','daily')}</div>`;};
UI.prototype.chart=function(values){const max=Math.max(1,...values);return `<svg class="income-chart" viewBox="0 0 600 140" preserveAspectRatio="none" role="img" aria-label="Recent production samples"><path class="chart-grid" d="M0 35H600M0 70H600M0 105H600"/><polyline points="${values.map((v,i)=>`${i*600/Math.max(1,values.length-1)},${130-v/max*115}`).join(' ')}"/></svg>`;};
UI.prototype.bankView=function(){const s=this.state.s;return `<div class="finance-top"><div><div class="eyebrow">AVAILABLE ENERGY</div><div class="finance-balance" data-bank-balance>${this.state.fmt(s.energy)}<small> E</small></div><span class="live-dot">Live facility ledger</span></div>${icon('chart')}</div><div class="metrics">${stat('Income / second',this.state.fmt(this.state.cps))}${stat('Income / minute',this.state.fmt(this.state.cps*60))}${stat('Lifetime earnings',this.state.fmt(s.lifetime))}${stat('Offline earnings',this.state.fmt(s.stats.offline))}</div><div class="chart-card"><div class="row between"><h3>Production history</h3><span class="muted">One sample / second · this session</span></div><div id="bankChart">${this.chart(this.incomeHistory||[0,0])}</div></div><p>Energy is your operating currency. Production continues while you manage your facility. Offline collection: ${Math.round(this.state.offlineEfficiency*100)}% for up to ${this.state.offlineHours} hours.</p>`;};
UI.prototype.workersView=function(){const m=data(this.state),s=this.state.s,names=['Jack','Maya','Noor','Theo','Ada','Finn'];return `<div class="staff-heading"><div><div class="eyebrow">PEOPLE & OPERATIONS</div><h2>A stronger shift.</h2><p>Assign specialists to a machine. Each training level adds 5% of its base output. One-time hiring and training costs; no recurring salary.</p></div><span class="tag">${m.workers.length} / 6 STAFF</span></div><div class="staff-grid">${names.map((name,id)=>{const w=m.workers.find(w=>w.id===id),cost=250*(id+1);return `<article class="card staff-card"><div class="portrait" style="--portrait:${['#cd9d75','#9dace1','#8ebfae'][id%3]}">${icon('staff')}<span>${name[0]}</span></div><span class="tag">${id<3?'SPECIALIST':'SENIOR SPECIALIST'} · ${w?'LEVEL '+w.level:'AVAILABLE'}</span><h3>${name}</h3><p>${w?'Output contribution: +'+w.level*5+'% of assigned machine base rate.':'Production specialist · +5% base machine output per level.'}</p>${w?`<label>Assigned machine<select data-worker="${id}"><option value="-1">Unassigned</option>${MACHINES.map((d,i)=>s.machines[i]>0?`<option value="${i}" ${w.machine===i?'selected':''}>${d.name}</option>`:'').join('')}</select></label><div class="cardfooter">${btn('Train · '+this.state.fmt(150*w.level)+' E','train',`data-id="${id}"`,s.energy<150*w.level||w.level>=20)}${btn('Dismiss','dismissconfirm',`data-id="${id}"`)}</div>`:btn('Hire · '+cost+' E','hire',`data-id="${id}"`,s.energy<cost)}</article>`;}).join('')}</div>`;};
UI.prototype.factoryView=function(){const i=this.machineIndex??0,d=MACHINES[i],s=this.state.s,l=s.machines[i];return `<div class="row between"><div><div class="eyebrow">PRODUCTION / ${d.area.toUpperCase()}</div><h2>${d.name}</h2></div><span class="tag">LEVEL ${l}</span></div><div class="production-line ${l?'running':''}"><div>${icon('box')}<span>01 / INPUT</span><h3>Raw energy</h3></div><div class="conveyor"><i></i><i></i><i></i></div><div>${icon('gear')}<span>02 / PROCESS</span><h3>${l?'Processing':'Awaiting construction'}</h3></div><div class="conveyor"><i></i><i></i><i></i></div><div>${icon('bolt')}<span>03 / OUTPUT</span><h3>Stored energy</h3></div></div><div class="metrics">${stat('Base energy / sec',this.state.fmt(this.state.machineRate(i)))}${stat('Milestone bonus',this.state.milestone(l)+'×')}${stat('Assigned staff',data(this.state).workers.filter(w=>w.machine===i).length)}${stat('Warehouse usage',Math.floor(data(this.state).stock.reduce((a,b)=>a+b,0))+' / 10K')}</div><div class="section-title">Expand this production line</div><div class="toolbar">${[1,10,100,'max'].map(n=>{const q=this.state.quote(i,n);return btn('+'+q.n+' levels · '+this.state.fmt(q.cost)+' E','machinebuy',`data-i="${i}" data-n="${n}"`,!this.state.fx.automation||s.energy<q.cost||!q.n);}).join('')}</div>${!this.state.fx.automation?`<p>Unlock Basic automation at the Upgrade Lab before constructing machines.</p>${btn('Visit upgrade lab','open','data-page="tree"')}`:''}<p>Machine milestones add equipment and improve output. Your network also sends materials to the warehouse while this session is running.</p>${btn('Network & infrastructure','open','data-page="control"')}`;};
UI.prototype.storageView=function(){const m=data(this.state),used=m.stock.reduce((a,b)=>a+b,0);const order=[0,1,2,3].sort((a,b)=>this.stockSort==='quantity'?m.stock[b]-m.stock[a]:this.stockSort==='value'?price(b)-price(a):this.stockSort==='rarity'?b-a:a-b);return `<div class="row between"><div><div class="eyebrow">WAREHOUSE CAPACITY</div><h2><span data-storage-used>${Math.floor(used)}</span> <span class="muted">/ 10,000</span></h2></div><select aria-label="Sort inventory" data-stock-sort>${['type','quantity','value','rarity'].map(x=>`<option ${this.stockSort===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="thin-bar storage-bar"><i style="width:${used/100}%"></i></div><p>${used>=9999?'Storage full. Sell materials at the Marketplace to resume collection.':'Materials arrive automatically from active machines. Inventory remains stored until sold.'}</p><div class="inventory-grid">${order.map(i=>`<div class="inventory-slot" style="--item:${materials[i][3]}">${icon('box')}<span class="tag">${materials[i][1]}</span><h3>${materials[i][0]}</h3><strong data-stock="${i}">× ${Math.floor(m.stock[i])}</strong><small>${this.state.fmt(price(i))} E / unit</small></div>`).join('')}${Array.from({length:4},()=>'<div class="inventory-slot empty">Reserved capacity</div>').join('')}</div>${btn('Open marketplace','open','data-page="market"')}`;};
UI.prototype.marketView=function(){const m=data(this.state);return `<div class="row between"><div><div class="eyebrow">MATERIAL EXCHANGE</div><h2>Put your surplus to work.</h2></div><span class="live-dot">Quotes update every 15 seconds</span></div><p>Sell whole units from your warehouse for energy. Prices move within ±12% of their base value.</p><div class="market-list">${materials.map((d,i)=>`<article class="market-row"><div class="market-symbol" style="color:${d[3]}">${icon('box')}</div><div><h3>${d[0]}</h3><span>${Math.floor(m.stock[i])} units in stock</span></div><div class="market-chart">${this.chart(Array.from({length:15},(_,j)=>d[2]*(1+.12*Math.sin((Math.floor(Date.now()/15000)-14+j)*.63+i*2))))}</div><div><strong>${price(i).toFixed(1)} E</strong><small class="${price(i)>=d[2]?'mint':'gold'}">${((price(i)/d[2]-1)*100).toFixed(1)}% vs base</small></div>${btn('Sell all','sell',`data-id="${i}"`,m.stock[i]<1)}</article>`).join('')}</div>`;};
const researchView=UI.prototype.researchView,collectionView=UI.prototype.collectionView,arcadeView=UI.prototype.arcadeView,rebirthView=UI.prototype.rebirthView;
UI.prototype.researchView=function(){return `<div class="research-banner"><div class="eyebrow">RESEARCH & DEVELOPMENT</div><h2>Tomorrow, engineered.</h2><p>Permanent knowledge. One active project. Five disciplines.</p></div>`+researchView.call(this).replace('class="grid"','class="research-tree"').replaceAll('<div class="card">','<div class="card research-node">')+`<div id="researchProgress"></div>`;};
UI.prototype.collectionView=function(){return `<div class="showroom-hero"><div class="eyebrow">COSMETIC SHOWROOM</div><h2>A signature of your own.</h2><p>Preview a reactor finish in the world before equipping or purchasing. Previewing does not spend currency.</p></div>`+collectionView.call(this).replaceAll('class="grid"','class="showroom-grid"').replace(/(<div class="card" style="text-align:center;--skin:([^"]+)">)/g,(match,tag,color)=>{const d=SKINS.find(s=>s[2]===color);return tag+(d?btn('Preview in world','preview',`data-id="${d[0]}"`):'');});};
UI.prototype.arcadeView=function(){return `<div class="arcade-banner">${icon('play')}<div><div class="eyebrow">OFF THE CLOCK</div><h2>One more round.</h2></div><span>${this.state.s.tokens} TOKENS</span></div>`+arcadeView.call(this);};
UI.prototype.rebirthView=function(){return `<div class="rebirth-hero"><div class="orbital"></div><div><div class="eyebrow">THE NEXT CYCLE</div><h2>End a chapter.<br>Begin beyond it.</h2><p>${this.state.fmt(this.state.s.run)} energy earned this run · ${this.state.s.machines.filter(n=>n>0).length} machines online</p></div></div><p class="reset-note">Rebirth also resets hired workers, stored materials and district arrangements. Cosmetics and achievements stay with you.</p>`+rebirthView.call(this);};
UI.prototype.settingsView=function(){const p=data(this.state).prefs;return `<div class="card management-settings"><h3>Camera & accessibility</h3><p>WASD / arrows or left / middle drag to pan. Scroll or pinch to zoom. Right drag to rotate. Home returns to headquarters. Tab opens headquarters; Escape closes the active screen.</p><label>Interface scale <select data-pref="scale">${[.85,1,1.15].map(v=>`<option value="${v}" ${p.scale===v?'selected':''}>${Math.round(v*100)}%</option>`).join('')}</select></label><label>Camera rotation <select data-pref="rotation">${[.5,1,1.5].map(v=>`<option value="${v}" ${p.rotation===v?'selected':''}>${v}×</option>`).join('')}</select></label><label>Notifications <input type="checkbox" data-pref="notifications" ${p.notifications?'checked':''}></label>${this.toggle('Reduced motion','reduced')}${this.toggle('Contextual tutorial','tutorial')}</div><div class="grid"><div class="card"><h3>Graphics</h3>${this.setting('Quality','quality',[['low','Low'],['medium','Medium'],['high','High'],['ultra','Ultra']])}${this.setting('Frame limit','fps',[[30,'30'],[60,'60'],[120,'120']])}${this.toggle('Production effects','particles')}${this.toggle('Shadows','shadows')}${this.toggle('Dynamic lighting','lighting')}${btn('Fullscreen','fullscreen')}</div><div class="card"><h3>Sound</h3>${this.toggle('Interface sounds','sound')}${this.toggle('Ambient music','music')}${this.range('Master volume','master',0,1,.05)}${this.range('Effects','sfx',0,1,.05)}${this.range('Music','musicVolume',0,1,.05)}</div><div class="card"><h3>Your progress</h3><p>Saved automatically every five seconds. Export a backup to keep a portable copy.</p><div class="toolbar">${btn('Save now','save')}${btn('Export','export')}${btn('Import','importdialog')}</div>${this.setting('Number format','notation',[['short','Compact'],['scientific','Scientific']])}${btn('Reset progress','resetconfirm')}<p>Offline income: ${Math.round(this.state.offlineEfficiency*100)}% efficiency · ${this.state.offlineHours}h maximum.</p>${btn('Save & return to title','exittitle')}</div></div>`;};
UI.prototype.restorePreview=function(){if(!this.previewSkin)return;this.previewSkin=null;this.world.sync();$('menu').classList.remove('previewing');$('previewBar')?.remove();};
UI.prototype.stopBuild=function(){this.buildMode=false;this.moveBuilding=null;this.buildTool=null;$('buildToolbar')?.remove();this.world.canvas.classList.remove('building');};
UI.prototype.action=async function(d){const m=data(this.state),s=this.state.s,id=Number(d.id);
 if(d.action==='exittitle'){this.state.save();this.close();this.started=false;this.world.paused=true;$('welcome').classList.remove('hidden');return;}
 if(d.action==='hire'){if(!Number.isInteger(id)||id<0||id>=6||m.workers.some(w=>w.id===id)||s.energy<250*(id+1))return;s.energy-=250*(id+1);m.workers.push({id,level:1,machine:-1});this.state.emit('sound',420);this.notice('Specialist hired. Assign a production line.');}
 else if(d.action==='train'){const w=m.workers.find(w=>w.id===id);if(!w||w.level>=20||s.energy<150*w.level)return;s.energy-=150*w.level;w.level++;this.notice('Training complete · level '+w.level);}
 else if(d.action==='dismissconfirm'){this.dialog(`<h2>Dismiss this specialist?</h2><p>The worker and their training will be removed. Hiring and training costs are not refunded.</p><div class="actions">${btn('Keep worker','closedialog')}${btn('Dismiss worker','dismiss',`data-id="${id}"`)}</div>`);return;}
 else if(d.action==='dismiss'){m.workers=m.workers.filter(w=>w.id!==id);this.closeDialog();}
 else if(d.action==='sell'){if(!Number.isInteger(id)||id<0||id>3)return;const n=Math.floor(m.stock[id]);if(!n)return;m.stock[id]-=n;const amount=n*price(id);this.state.gain(amount);this.notice('Sold '+n+' '+materials[id][0]+' · +'+this.state.fmt(amount)+' energy');}
 else if(d.action==='preview'){const skin=SKINS.find(s=>s[0]===d.id);if(!skin)return;this.previewSkin=skin[0];this.world.coreSphere.material=this.world.mat(skin[2],true);this.world.goal.set(0,0,-2);this.world.goalSize=19;$('menu').classList.add('previewing');$('previewBar')?.remove();const bar=document.createElement('div');bar.id='previewBar';bar.innerHTML=`<span>Preview · ${skin[1]}</span>${btn('Return to showroom','endpreview')}`;document.body.append(bar);return;}
 else if(d.action==='endpreview'){this.restorePreview();return;}
 else if(d.action==='buildmode'){this.close();this.buildMode=true;const el=document.createElement('div');el.id='buildToolbar';el.innerHTML=`<span>BUILD MODE</span>${btn('Move buildings','buildtool','data-tool="move"')}${btn('Decorations','buildtool','data-tool="planter"')}${btn('Roads','buildtool','data-tool="road"')}${btn('Utility lights','buildtool','data-tool="light"')}${btn('Done','endbuild')}<small id="buildHelp">Select a building, then click an open space. Cosmetic arrangements are free.</small>`;document.body.append(el);this.buildTool='move';return;}
 else if(d.action==='buildtool'){this.buildTool=d.tool;this.moveBuilding=null;$('buildHelp').textContent=d.tool==='move'?'Select a building, then click an open space.':'Click open ground in the central district to place. Maximum 50 decorations.';return;}
 else if(d.action==='endbuild'){this.stopBuild();this.state.save();return;}
 else if(d.action==='machinebuy'&&this.page==='factory'){this.state.buyMachine(Number(d.i),d.n==='max'?'max':Number(d.n));this.render();return;}
 else {await action.call(this,d);if(d.action==='resetdo')this.world.syncLayout();if(this.opened){$('menuTitle').textContent=names[this.page]||$('menuTitle').textContent;}return;}
 this.state.save();this.render();
};
UI.prototype.place=function(p){if(!this.buildMode||!p)return;const m=data(this.state),x=Math.round(p.x),z=Math.round(p.z);if(Math.abs(x)>18||Math.abs(z)>18){this.notice('Place within the central district.');return;}const collision=this.world.interactables.some(g=>{if(g===this.moveBuilding)return false;const pos=g.getWorldPosition(new THREE.Vector3());return Math.abs(pos.x-x)<4.6&&Math.abs(pos.z-z)<4.4;});if(collision){this.notice('Leave some space around other buildings and equipment.');return;}
 if(this.moveBuilding){const g=this.moveBuilding;m.layout[g.userData.facility]=[x,z];this.moveBuilding=null;this.notice('Building relocated.');}else if(this.buildTool!=='move'&&m.decor.length<50){m.decor.push({type:this.buildTool,x,z});}else return;this.world.syncLayout();this.state.save();
};
UI.prototype.update=function(dt){update.call(this,dt);if(!this.managementReady){this.managementReady=true;this.incomeHistory=[];document.querySelector('.settings-button').innerHTML=icon('gear');this.state.on((type,p)=>{if(type==='groundclick')this.place(p);});document.addEventListener('change',e=>{if(e.target.dataset.worker!==undefined){const w=data(this.state).workers.find(w=>w.id===Number(e.target.dataset.worker)),i=Number(e.target.value);if(w&&(i===-1||this.state.s.machines[i]>0))w.machine=i;this.state.save();}if(e.target.hasAttribute('data-stock-sort')){this.stockSort=e.target.value;this.render();}if(e.target.dataset.pref){const key=e.target.dataset.pref;data(this.state).prefs[key]=key==='notifications'?e.target.checked:Number(e.target.value);this.state.save();}});document.addEventListener('keydown',e=>{if(e.code==='Escape'){if(this.previewSkin){e.stopImmediatePropagation();this.restorePreview();return;}if(this.buildMode)this.stopBuild();}if(e.code==='Tab'&&this.opened){e.stopImmediatePropagation();const elements=[...$('menu').querySelectorAll('button:not(:disabled),select,input,textarea')].filter(el=>el.offsetParent!==null);if(elements.length){e.preventDefault();const at=elements.indexOf(document.activeElement);elements[(at+(e.shiftKey?-1:1)+elements.length)%elements.length].focus();}}},true);$('dialog').addEventListener('cancel',()=>{this.world.selection.visible=false;this.world.selectedBuilding=null;});$('menu').addEventListener('click',e=>{if(e.target===$('menu'))this.close();});$('world').addEventListener('pointerdown',()=>{this.world.state.s.settings.sensitivity=data(this.state).prefs.rotation;});}
 const m=data(this.state);document.documentElement.style.setProperty('--ui-scale',m.prefs.scale);this.managementClock=(this.managementClock||0)+dt;
 if(this.managementClock>=1){this.managementClock=0;this.incomeHistory.push(this.state.cps);if(this.incomeHistory.length>60)this.incomeHistory.shift();if(this.opened&&this.page==='bank'){$('bankChart').innerHTML=this.chart(this.incomeHistory);document.querySelector('[data-bank-balance]').textContent=this.state.fmt(this.state.s.energy)+' E';}if(this.opened&&this.page==='research'&&this.researchSignature!==JSON.stringify([this.state.s.research,this.state.s.researchJob])){this.researchSignature=JSON.stringify([this.state.s.research,this.state.s.researchJob]);this.render();}if(this.opened&&this.page==='research'&&this.state.s.researchJob){const job=this.state.s.researchJob,full=RESEARCH[job.i][3],left=Math.max(0,(job.end-Date.now())/1000);$('researchProgress').innerHTML=`<div class="progress-label"><span>${RESEARCH[job.i][0]}</span><span>${timeLabel(left)} remaining</span></div><div class="thin-bar"><i style="width:${(1-left/full)*100}%"></i></div>`;}if(this.opened&&['storage','market'].includes(this.page)&&!$('dialog').open)this.render();}
 const objective=document.querySelector('.objective');objective.hidden=!this.started||!this.state.s.settings.tutorial||this.opened||m.tutorial>=3;if(!objective.hidden){if(this.state.s.stats.clicks>0)m.tutorial=Math.max(m.tutorial,1);if(this.state.s.machines[0]>0)m.tutorial=Math.max(m.tutorial,2);if(this.state.s.stats.passive>5)m.tutorial=3;const hints=['Click the glowing reactor to create energy.','Visit the Upgrade Lab. Unlock Basic automation, then build your first machine.','Your first machine is running. Watch your profits arrive.'];$('objectiveLabel').textContent='YOUR FIRST SHIFT';$('objectiveText').textContent=hints[m.tutorial]||'Facility online.';}
 if(this.world.current?.obj.userData.facility){$('interactSub').textContent=this.buildMode?'Click to relocate':'Click to manage';}
};
