import {VERSION,SAVE_KEY,LIMIT,NODES,NODE_MAP,AREAS,MACHINES,SKINS,DRONES,FACILITY,RESEARCH,NPC_QUESTS} from './data.js';
export const cap=n=>Math.min(LIMIT,Math.max(0,Number.isFinite(n)?n:LIMIT));
export function format(n,notation='short'){if(!Number.isFinite(n))return 'MAX';if(n<1000)return n<10?Number(n.toFixed(1)).toString():Math.floor(n).toLocaleString('en');if(notation==='scientific')return n.toExponential(2);const u=['','K','M','B','T','Qa','Qi','Sx','Sp','Oc','No','Dc'],i=Math.floor(Math.log10(n)/3);return i<u.length?(n/1000**i).toFixed(2).replace(/\.?0+$/,'')+u[i]:n.toExponential(2);}
export const timeLabel=n=>n>=3600?`${Math.floor(n/3600)}h ${Math.floor(n%3600/60)}m`:n>=60?`${Math.floor(n/60)}m ${Math.floor(n%60)}s`:`${Math.ceil(n)}s`;
export function initial(){return {version:VERSION,energy:0,lifetime:0,run:0,dust:0,tokens:0,cores:0,coreTotal:0,shards:0,xp:0,points:1,pointsEarned:1,rebirths:0,cycle:0,ascensions:0,reality:0,skills:{},firstSkills:[],machines:Array(10).fill(0),facility:Array(5).fill(0),research:Array(5).fill(0),researchJob:null,areas:['lab'],discovered:['lab'],collected:[],secrets:[],skins:['azure'],skin:'azure',outfit:0,droneCopies:Array(5).fill(0),droneLevels:Array(5).fill(0),equipped:[],slots:1,achievements:[],npcClaims:[],boosts:[],respecs:0,challenge:null,completedChallenges:[],last:Date.now(),position:{x:0,y:0,z:7,yaw:0,pitch:0},daily:{date:'',streak:0},quests:{day:'',week:'',daily:{},weekly:{},claims:[]},stats:{clicks:0,criticals:0,highest:0,passive:0,time:0,offline:0,purchases:0,games:0,wins:0,bosses:0,quests:0,events:0,npcTalks:0,memory:0,parkour:0,combo:1},settings:{view:'first',quality:'high',particles:true,bloom:true,shadows:true,antialias:true,lighting:true,renderDistance:150,motionBlur:false,shake:true,bob:true,reduced:false,fps:60,sensitivity:1,sound:true,music:false,master:.4,sfx:.5,musicVolume:.18,notation:'short',accent:'#79dfc4',machineColor:'#6f8fa5',trail:true,tutorial:true}};}
export class State{
 constructor(){this.s=initial();this.listeners=[];this.fx={};this.combo=0;this.lastClick=0;this.lastProductionRoll=0;this.lastMining=0;this.resetting=false;this.storageFailed=false;this.achDefs=this.makeAchievements();this.load();this.calendar();this.recompute();}
 on(fn){this.listeners.push(fn);}emit(type,data){this.listeners.forEach(fn=>fn(type,data));}notice(t){this.emit('notice',t);}get level(){return 1+Math.floor(Math.sqrt(this.s.xp/35));}fmt(n){return format(n,this.s.settings.notation);}
 recompute(){const f={};for(const [id,l]of Object.entries(this.s.skills)){const n=NODE_MAP[id];if(n)for(const [k,v]of Object.entries(n.effects))f[k]=(f[k]||0)+v*l;}this.s.facility.forEach((l,i)=>{const k=FACILITY[i][2];f[k]=(f[k]||0)+l*(i===2||i===3?1:.1);});this.s.research.forEach((l,i)=>{const k=RESEARCH[i][4];f[k]=(f[k]||0)+l*.25;});this.fx=f;this.emit('change');}
 buff(type){return this.s.boosts.filter(b=>b.type===type&&b.end>Date.now()).reduce((a,b)=>Math.max(a,b.mult),1);}
 drone(i){return this.s.equipped.includes(i)?(1+this.s.droneLevels[i]*.5)*(1+(this.fx.dronePower||0)):0;}
 get global(){return cap((1+this.s.coreTotal*.08*(this.fx.immortal?2:1))*(1+this.s.ascensions*2)*(1+this.s.reality*10)*(1+(this.fx.global||0))*(1+this.s.achievements.length*.005)*(1+this.s.completedChallenges.length*.1)*(1+.08*this.drone(4))*(this.s.skin==='gold'?1.02:1)*this.buff('all'));}
 get manual(){let n=(1+(this.fx.click||0))*this.global*this.buff('click');if(this.fx.manualKeystone)n*=10;if(this.fx.machineKeystone)n*=.2;if(this.fx.god)n*=8;return cap(n);}
 get crit(){return Math.min(.85,(this.fx.critUnlock?.05:0)+(this.fx.crit||0)+this.drone(1)*.02+(this.buff('luck')>1?.3:0));}
 get critMult(){return 5+(this.fx.critMult||0);}
 milestone(n){return 2**[10,25,50,100,250,500,1000].filter(x=>n>=x).length;}
 machineRate(i){return cap(this.s.machines[i]*MACHINES[i].rate*this.milestone(this.s.machines[i]));}
 get passive(){if(!this.fx.automation||this.s.challenge?.id==='manual')return 0;let n=this.s.machines.reduce((a,l,i)=>cap(a+this.machineRate(i)),0)*(1+(this.fx.passive||0))*this.global*(1+this.drone(0)*.05)*this.buff('passive');if(this.fx.selfImprove)n*=1+Math.min(1,this.s.stats.time/6000);if(this.fx.machineKeystone)n*=5;if(this.fx.manualKeystone)n*=.5;if(this.fx.fullAuto)n*=8;if(this.fx.dimensionProduction)n*=1+this.s.ascensions*this.fx.dimensionProduction;if(this.s.challenge?.id==='instability')n*=1+.7*Math.sin(this.s.stats.time);return cap(n);}
 get auto(){return this.s.challenge?.id==='manual'?0:cap((this.fx.autoClicks||0)*this.manual);}
 get cps(){return cap(this.passive+this.auto);}
 get offlineEfficiency(){return this.fx.neverOffline?1:Math.min(1,this.fx.offline||0);}
 get offlineHours(){return Math.min(48,8+(this.fx.hours||0));}
 gain(n,passive=false){n=cap(n);for(const k of ['energy','lifetime','run'])this.s[k]=cap(this.s[k]+n);if(passive)this.s.stats.passive=cap(this.s.stats.passive+n);this.q('earn',n);if(this.s.challenge)this.s.challenge.earned=cap(this.s.challenge.earned+n);}
 xp(n){const old=this.level;this.s.xp=cap(this.s.xp+n*(1+(this.fx.xp||0))*this.buff('xp'));const delta=this.level-old;if(delta){let points=delta*(1+(this.fx.levelPoints||0));for(let l=old+1;l<=this.level;l++){if(l%10===0)points+=3;}this.addPoints(points);this.s.dust+=delta;this.q('level',delta);this.notice(`Level ${this.level} · +${points} Skill Points`);this.emit('level');}}
 addPoints(n){this.s.points+=n;this.s.pointsEarned+=n;}
 pulse(){if(this.s.challenge?.id==='machine')return {value:0,critical:false};const now=performance.now();this.combo=Math.min(100,this.combo+(now-this.lastClick<550?8:3));this.lastClick=now;const crit=Math.random()<this.crit;this.s.stats.clicks++;let value=this.manual*(1+this.combo/100*(2+(this.fx.combo||0)))*(crit?this.critMult:1);if(this.fx.tenth&&this.s.stats.clicks%10===0)value*=5;if(this.fx.jackpot&&Math.random()<.002){value*=100;this.notice('JACKPOT PULSE · 100× energy');}this.gain(value);this.s.stats.highest=Math.max(this.s.stats.highest,cap(value));this.s.stats.combo=Math.max(this.s.stats.combo,1+this.combo/50);this.q('click');if(crit){this.s.stats.criticals++;this.q('crit');}this.xp(4);this.emit('pulse',{value:cap(value),critical:crit});return {value:cap(value),critical:crit};}
 nodeCost(n){const l=this.s.skills[n.id]||0;return n.tree==='mastery'?Math.ceil(n.cost*(1+l*.35)):n.tree==='quantum'?Math.ceil(n.cost*1.35**l):n.cost;}
 available(n){if((this.s.skills[n.id]||0)>=n.max)return false;if(n.tree==='quantum'&&!this.s.rebirths)return false;if(n.tree==='ascension'&&!this.s.ascensions)return false;if(n.tree==='mastery'&&this.level<100)return false;if(this.s.challenge?.id==='branch'&&n.tree==='main'&&n.branch!=='cross'){const branches=new Set(Object.keys(this.s.skills).filter(id=>NODE_MAP[id]?.tree==='main').map(id=>NODE_MAP[id].branch));if(branches.size&&!branches.has(n.branch))return false;}return n.requires.every(id=>(this.s.skills[id]||0)>0);}
 skillBuy(id){const n=NODE_MAP[id];if(!n||!this.available(n))return false;const currency=n.tree==='quantum'?'cores':n.tree==='ascension'?'shards':'points',cost=this.nodeCost(n);if(this.s[currency]<cost)return false;this.s[currency]-=cost;this.s.skills[id]=(this.s.skills[id]||0)+1;if(!this.s.firstSkills.includes(id)){this.s.firstSkills.push(id);this.xp(8);this.q('node');}this.recompute();this.notice(`${n.name} · level ${this.s.skills[id]}`);this.emit('skill',id);this.progress();this.save();return true;}
 respec(){if(this.s.respecs&&this.s.dust<25)return false;const ids=Object.keys(this.s.skills).filter(id=>NODE_MAP[id].tree==='main');let refund=0;ids.forEach(id=>{refund+=this.s.skills[id]*NODE_MAP[id].cost;delete this.s.skills[id];});if(this.s.respecs)this.s.dust-=25;this.s.points+=refund;this.s.respecs++;this.recompute();this.s.areas=['lab'];this.progress();this.emit('teleport','lab');this.notice(`${refund} Skill Points refunded`);this.save();return true;}
 quote(i,amount=1){const d=MACHINES[i],l=this.s.machines[i],remaining=10000-l;const total=n=>cap(d.base*d.growth**l*(d.growth**n-1)/(d.growth-1));let n=Math.min(amount==='max'?remaining:amount,remaining);if(amount==='max'){let lo=0,hi=remaining;while(lo<hi){const mid=Math.ceil((hi+lo)/2);if(total(mid)<=this.s.energy)lo=mid;else hi=mid-1;}n=lo;}return {n,cost:n?total(n):0};}
 buyMachine(i,amount){if(!this.fx.automation||!this.s.areas.includes(MACHINES[i].area))return false;const q=this.quote(i,amount);if(q.n<1||this.s.energy<q.cost)return false;this.s.energy-=q.cost;this.s.machines[i]+=q.n;this.s.stats.purchases+=q.n;this.q('buy',q.n);this.xp(q.n*6);this.emit('machine',i);this.progress();return true;}
 facilityBuy(i){const cost=1000*2**this.s.facility[i];if(this.s.energy<cost||this.s.facility[i]>=50)return;this.s.energy-=cost;this.s.facility[i]++;this.recompute();this.emit('world');this.xp(15);}
 startResearch(i){if(this.s.researchJob)return;const d=RESEARCH[i],cost=d[2]*2**this.s.research[i];if(this.s.energy<cost||this.s.research[i]>=20)return;this.s.energy-=cost;this.s.researchJob={i,end:Date.now()+d[3]*1000};this.notice('Research started · '+d[0]);this.emit('change');}
 get rebirthRequirement(){return 1e6*Math.pow(1.15,this.s.cycle);}
 get rebirthGain(){return Math.floor(Math.sqrt(this.s.run/this.rebirthRequirement)*(1+(this.fx.prestige||0))*(1+.1*this.drone(3)));}
 performRebirth(){if(this.s.run<this.rebirthRequirement)return 0;const n=this.rebirthGain;this.s.cores+=n;this.s.coreTotal+=n;this.s.rebirths++;this.s.cycle++;this.addPoints(2+(this.fx.rebirthPoints||0));this.s.energy=this.fx.startEnergy||0;this.s.run=0;const keep=Math.min(.8,this.fx.memory||0);this.s.machines=this.s.machines.map(l=>Math.floor(l*keep));this.s.machines[0]+=this.fx.startMachine||0;this.s.facility.fill(0);this.s.areas=['lab'];this.s.boosts=[];this.s.challenge=null;this.s.researchJob=null;this.combo=0;this.q('rebirth');this.xp(150);this.recompute();this.emit('world');this.emit('teleport','lab');this.progress();this.save();return n;}
 ascend(){if(this.s.cycle<10)return false;this.s.ascensions++;this.s.shards+=3;this.s.cycle=0;this.s.cores=0;this.s.coreTotal=0;for(const id of Object.keys(this.s.skills))if(NODE_MAP[id].tree==='quantum')delete this.s.skills[id];this.s.energy=0;this.s.run=0;this.s.machines.fill(0);this.s.facility.fill(0);this.s.research.fill(0);this.s.researchJob=null;this.s.boosts=[];this.s.challenge=null;this.s.areas=['lab'];this.addPoints(5);this.recompute();this.emit('world');this.emit('teleport','lab');this.progress();this.save();return true;}
 newReality(){if(this.s.ascensions<3||!this.fx.breakReality||!this.fx.multiverse)return false;const old=this.s;this.s=initial();this.s.reality=old.reality+1;this.s.skins=[...new Set([...old.skins,'reality'])];this.s.skin='reality';this.s.settings=old.settings;this.s.achievements=old.achievements;this.s.stats=old.stats;this.s.lifetime=old.lifetime;this.s.secrets=old.secrets;this.s.points=6+this.s.reality*2;this.s.pointsEarned=this.s.points;this.recompute();this.emit('world');this.emit('teleport','lab');this.notice('NEW REALITY · All-energy multiplier increased');this.save();return true;}
 challengeStart(id){this.s.challenge={id,start:Date.now(),earned:0};this.s.energy=0;this.s.run=0;this.s.machines.fill(0);this.s.boosts=[];if(id==='machine'){this.s.machines[0]=1;if(!this.fx.automation){this.s.challenge=null;this.notice('Unlock Basic automation first.');return;}}this.emit('world');this.emit('teleport','lab');}
 addBoost(type,mult,seconds){const old=this.s.boosts.find(b=>b.type===type&&b.mult===mult);if(old)old.end=Math.max(Date.now(),old.end)+seconds*1000;else this.s.boosts.push({type,mult,end:Date.now()+seconds*1000});this.emit('change');}
 collect(id){if(this.s.collected.includes(id))return;this.s.collected.push(id);this.s.dust+=2;this.xp(15);this.q('shard');if(this.s.collected.length%5===0)this.addPoints(1);if(this.s.collected.length>=50)this.unlockSkin('reality');this.notice(`Energy shard ${this.s.collected.length}/50 · +2 stardust`);this.emit('collected',id);this.progress();}
 secret(id){if(this.s.secrets.includes(id))return;this.s.secrets.push(id);this.addPoints(2);this.s.dust+=10;this.notice('Hidden discovery · +2 Skill Points · +10 stardust');if(id==='terminal')this.unlockSkin('developer');this.progress();}
 unlockSkin(id){if(this.s.skins.includes(id))return;this.s.skins.push(id);this.notice('Reactor skin unlocked · '+SKINS.find(d=>d[0]===id)[1]);}
 buySkin(id){const d=SKINS.find(d=>d[0]===id);if(!d)return;if(!this.s.skins.includes(id)){if(d[4]<0||this.s.dust<d[4])return;this.s.dust-=d[4];this.unlockSkin(id);}this.s.skin=id;this.emit('world');}
 droneBuy(i){if(this.s.dust<DRONES[i][3])return;this.s.dust-=DRONES[i][3];this.s.droneCopies[i]++;if(!this.s.equipped.includes(i)&&this.s.equipped.length<this.s.slots)this.s.equipped.push(i);this.emit('world');}
 droneFuse(i){if(this.s.droneCopies[i]<3||this.s.droneLevels[i]>=10)return;this.s.droneCopies[i]-=2;this.s.droneLevels[i]++;this.notice('Drone evolved · '+DRONES[i][0]);this.emit('world');}
 npcTalk(id){this.s.stats.npcTalks++;if(this.s.stats.npcTalks>=100)this.secret('social');return NPC_QUESTS.find(q=>q[0]===id);}
 npcValue(q){return q[3]==='lifetime'?this.s.lifetime:q[3]==='nodes'?Object.keys(this.s.skills).length:q[3]==='machines'?this.s.machines.reduce((a,b)=>a+b,0):this.s.discovered.length;}
 npcClaim(id){const q=NPC_QUESTS.find(d=>d[0]===id);if(!q||this.npcValue(q)<q[4]||this.s.npcClaims.includes(id))return;this.s.npcClaims.push(id);this.addPoints(3);this.s.dust+=15;this.s.stats.quests++;this.xp(100);this.notice('Assignment complete · +3 Skill Points · +15 stardust');}
 calendar(){const date=new Date(),day=date.toISOString().slice(0,10);date.setUTCDate(date.getUTCDate()-(date.getUTCDay()+6)%7);const week=date.toISOString().slice(0,10);if(this.s.quests.day!==day){this.s.quests.day=day;this.s.quests.daily={};this.s.quests.claims=this.s.quests.claims.filter(id=>id.startsWith('w'));}if(this.s.quests.week!==week){this.s.quests.week=week;this.s.quests.weekly={};this.s.quests.claims=this.s.quests.claims.filter(id=>id.startsWith('d'));}return day;}
 q(key,n=1){for(const p of ['daily','weekly'])this.s.quests[p][key]=cap((this.s.quests[p][key]||0)+n);}
 missions(){return [['d0','daily','earn',1e7,'Generate 10M energy'],['d1','daily','buy',25,'Buy 25 machine levels'],['d2','daily','node',2,'Unlock 2 skill nodes'],['d3','daily','game',1,'Complete a minigame'],['d4','daily','shard',3,'Find 3 energy shards'],['w0','weekly','rebirth',5,'Rebirth 5 times'],['w1','weekly','boss',10,'Defeat 10 bosses'],['w2','weekly','game',20,'Complete 20 minigames'],['w3','weekly','level',20,'Gain 20 levels']];}
 claimMission(id){const m=this.missions().find(m=>m[0]===id);if(!m||this.s.quests.claims.includes(id)||(this.s.quests[m[1]][m[2]]||0)<m[3])return;this.s.quests.claims.push(id);const n=m[1]==='daily'?1:3;this.addPoints(n);this.s.dust+=n*5;this.s.stats.quests++;this.xp(n*50);this.notice(`Mission complete · +${n} Skill Points`);}
 dailyClaim(){const day=this.calendar();if(this.s.daily.date===day)return false;const yesterday=new Date(Date.now()-864e5).toISOString().slice(0,10);this.s.daily.streak=this.s.daily.date===yesterday?this.s.daily.streak+1:1;this.s.daily.date=day;const d=(this.s.daily.streak-1)%7+1;if(d===1)this.gain(Math.max(100,this.cps*60));if(d===2)this.addBoost('all',2,300);if(d===3)this.xp(200);if(d===4)this.s.tokens+=20;if(d===5)this.s.droneCopies[0]++;if(d===6){this.s.cores++;this.s.coreTotal++;}if(d===7){this.unlockSkin('galaxy');this.s.dust+=25;}this.notice('Day '+d+' supply claimed');this.save();return true;}
 progress(){for(const a of AREAS)if(!this.s.areas.includes(a.id)&&this.s.run>=a.need&&(!a.flag||this.fx[a.flag])){this.s.areas.push(a.id);if(!this.s.discovered.includes(a.id)){this.s.discovered.push(a.id);this.xp(60);this.addPoints(1);}this.notice('AREA UNLOCKED · '+a.name);this.emit('area',a.id);}for(const a of this.achDefs)if(!this.s.achievements.includes(a.id)&&a.value()>=a.goal){this.s.achievements.push(a.id);this.s.dust+=a.reward;if(this.s.achievements.length%5===0)this.addPoints(1);this.notice('Achievement · '+a.name);}if(this.s.rebirths>=1)this.unlockSkin('toxic');if(this.s.rebirths>=10)this.unlockSkin('void');if(this.s.ascensions>=1)this.unlockSkin('blackhole');if(this.level>=50)this.unlockSkin('frozen');if(this.s.challenge){const c=this.s.challenge;if(c.earned>=1e6){if(!this.s.completedChallenges.includes(c.id)){this.s.completedChallenges.push(c.id);this.addPoints(3);}this.s.dust+=20;this.s.challenge=null;this.notice('Challenge complete · +20 stardust');}else if(c.id==='speed'&&Date.now()-c.start>180000){this.s.challenge=null;this.notice('Speed challenge expired.');}}}
 tick(dt){if(!this.resetting||this.fx.temporal)this.gain(this.cps*dt,true);this.s.stats.time+=dt;if(performance.now()-this.lastClick>450)this.combo=Math.max(0,this.combo-dt*16);this.lastProductionRoll+=dt;if(this.lastProductionRoll>=1){this.lastProductionRoll=0;if(this.fx.luckyMachine&&Math.random()<.05)this.gain(this.passive,true);this.progress();}this.lastMining+=dt;if(this.lastMining>=60){this.lastMining=0;if(this.drone(2)){this.gain(Math.max(100,this.cps*10)*this.drone(2));this.notice('Mining drone delivered an energy cache');}}if(this.s.researchJob&&Date.now()>=this.s.researchJob.end){const i=this.s.researchJob.i;this.s.research[i]++;this.s.researchJob=null;this.recompute();this.xp(80);this.notice('Research complete · '+RESEARCH[i][0]);}}
 makeAchievements(){const out=[];const set=(key,name,goals,val)=>goals.forEach((goal,i)=>out.push({id:key+i,name:`${name} ${i+1}`,goal,value:val,reward:2+i,desc:`${name} · ${format(goal)}`}));set('energy','Energy pioneer',[1,100,1000,1e4,1e5,1e6,1e7,1e8,1e9,1e12,1e15,1e18],()=>this.s.lifetime);set('click','Pulse technician',[10,100,500,1000,5000,10000,50000,1e5,1e6],()=>this.s.stats.clicks);set('machine','Industrial revolution',[1,10,25,50,100,250,500,1000],()=>this.s.machines.reduce((a,b)=>a+b,0));set('node','Knowledge is power',[1,5,10,25,50,75,100,130],()=>Object.keys(this.s.skills).length);set('rebirth','Reborn',[1,3,5,10,25,50,100],()=>this.s.rebirths);set('area','Explorer',[2,3,5,7,10],()=>this.s.discovered.length);set('shard','Crystal collector',[1,5,10,25,50],()=>this.s.collected.length);set('boss','Boss slayer',[1,3,7,10,25,50],()=>this.s.stats.bosses);set('game','Arcade regular',[1,5,10,25,50,100],()=>this.s.stats.games);set('crit','Critical thinker',[10,100,1000,10000],()=>this.s.stats.criticals);set('time','Dedicated engineer',[600,3600,18000],()=>this.s.stats.time);set('asc','Ascended',[1,3,10],()=>this.s.ascensions);out.push({id:'memory',name:'Perfect stabilisation',goal:8,value:()=>this.s.stats.memory,reward:15,desc:'Complete eight stabilisation rounds.'},{id:'secret',name:'Under the surface',goal:3,value:()=>this.s.secrets.length,reward:20,desc:'Find three world secrets.'},{id:'reality',name:'Reality breaker',goal:1,value:()=>this.s.reality,reward:30,desc:'Enter a New Reality.'});return out;}
 validate(raw){if(raw?.version===1)return this.migrate(raw);if(!raw||raw.version!==VERSION)throw Error('This is not a Nova Foundry 3D save.');const out=initial();const n=(v,max=LIMIT,integer=false)=>{if(typeof v!=='number'||!Number.isFinite(v)||v<0||v>max||(integer&&!Number.isInteger(v)))throw Error('Invalid numeric data in save.');return v;};for(const k of ['energy','lifetime','run','dust','tokens','cores','coreTotal','shards','xp','points','pointsEarned','rebirths','cycle','ascensions','reality','respecs','last'])out[k]=n(raw[k]);for(const k of ['machines','facility','research','droneCopies','droneLevels']){if(!Array.isArray(raw[k])||raw[k].length!==out[k].length)throw Error('Invalid array: '+k);out[k]=raw[k].map(v=>n(v,k==='machines'?10000:k==='droneLevels'?10:1000000,true));}if(!raw.skills||typeof raw.skills!=='object')throw Error('Missing skills.');for(const [id,v]of Object.entries(raw.skills)){if(!NODE_MAP[id])throw Error('Unknown skill.');out.skills[id]=n(v,NODE_MAP[id].max,true);}
 const lists={firstSkills:NODES.map(n=>n.id),areas:AREAS.map(a=>a.id),discovered:AREAS.map(a=>a.id),skins:SKINS.map(d=>d[0]),equipped:[0,1,2,3,4],achievements:this.achDefs.map(a=>a.id),npcClaims:NPC_QUESTS.map(q=>q[0]),completedChallenges:['manual','machine','instability','speed','branch'],secrets:['reactortop','tunnel','terminal','social','hidden']};for(const [k,allowed]of Object.entries(lists)){if(!Array.isArray(raw[k]))throw Error('Missing '+k);out[k]=[...new Set(raw[k].filter(v=>allowed.includes(v)))];}if(!Array.isArray(raw.collected))throw Error('Missing shard data.');out.collected=[...new Set(raw.collected.map(v=>n(v,49,true)))];out.slots=n(raw.slots,3,true)||1;out.equipped=out.equipped.filter(i=>out.droneCopies[i]>0).slice(0,out.slots);out.skin=out.skins.includes(raw.skin)?raw.skin:'azure';if(!out.skins.includes('azure'))out.skins.push('azure');out.outfit=n(raw.outfit,7,true);for(const k of Object.keys(out.stats))out.stats[k]=n(raw.stats?.[k]);
 for(const k of Object.keys(out.settings)){const v=raw.settings?.[k];if(typeof out.settings[k]==='boolean'&&typeof v==='boolean')out.settings[k]=v;}for(const k of ['master','sfx','musicVolume'])out.settings[k]=n(raw.settings?.[k],1);out.settings.sensitivity=n(raw.settings?.sensitivity,3);const enums={view:['first','third'],quality:['low','medium','high','ultra'],notation:['short','scientific'],fps:[30,60,120],renderDistance:[75,150,250],accent:['#79dfc4','#72d8ee','#c2a4ff','#f3c87d'],machineColor:['#6f8fa5','#bf815e','#849a71','#9982b2']};for(const [k,choices]of Object.entries(enums))if(choices.includes(raw.settings?.[k]))out.settings[k]=raw.settings[k];
 const date=v=>typeof v==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(v)?v:'';out.daily={date:date(raw.daily?.date),streak:n(raw.daily?.streak??0,1e6,true)};out.quests.day=date(raw.quests?.day);out.quests.week=date(raw.quests?.week);for(const p of ['daily','weekly'])for(const key of ['earn','click','crit','buy','node','game','shard','rebirth','boss','level'])out.quests[p][key]=n(raw.quests?.[p]?.[key]??0);out.quests.claims=(raw.quests?.claims||[]).filter(id=>this.missions().some(m=>m[0]===id));if(!Array.isArray(raw.boosts)||raw.boosts.length>50)throw Error('Invalid boosts.');out.boosts=raw.boosts.map(b=>{if(!['all','click','passive','xp','luck'].includes(b.type))throw Error('Invalid boost type.');return {type:b.type,mult:n(b.mult,10),end:n(b.end,Date.now()+7*864e5)};});if(raw.researchJob)out.researchJob={i:n(raw.researchJob.i,4,true),end:n(raw.researchJob.end,Date.now()+864e5)};if(raw.challenge&&['manual','machine','instability','speed','branch'].includes(raw.challenge.id))out.challenge={id:raw.challenge.id,start:n(raw.challenge.start,Date.now()+864e5),earned:n(raw.challenge.earned)};if(raw.position)for(const k of ['x','y','z','yaw','pitch']){const v=raw.position[k];if(typeof v==='number'&&Number.isFinite(v)&&Math.abs(v)<1000)out.position[k]=v;}return out;}
 migrate(raw){const s=initial();for(const k of ['energy','lifetime','run','xp','cores','coreTotal','tokens','rebirths','ascensions']){if(typeof raw[k]!=='number'||!Number.isFinite(raw[k])||raw[k]<0)throw Error('Invalid classic save.');s[k]=cap(raw[k]);}s.dust=cap(raw.gems||0);s.points=1+Math.floor(Math.sqrt(s.xp/35))+s.rebirths*2;s.pointsEarned=s.points;s.machines[0]=Math.min(10000,Math.max(0,Math.floor(raw.generators?.[0]||0)));if(s.machines[0]){s.skills['auto-0']=1;}s.stats.clicks=cap(raw.stats?.clicks||0);return s;}
 offline(){this.recompute();const sec=Math.min(this.offlineHours*3600,Math.max(0,(Date.now()-this.s.last)/1000));const buffs=this.s.boosts;this.s.boosts=[];const amount=this.cps*sec*this.offlineEfficiency*(1+(this.fx.offlineProduction||0));this.s.boosts=buffs.filter(b=>b.end>Date.now());if(sec>20&&amount>0){this.gain(amount,true);this.s.stats.offline=cap(this.s.stats.offline+amount);this.pendingOffline={seconds:sec,amount:cap(amount)};}this.s.last=Date.now();}
 save(){this.s.last=Date.now();try{localStorage.setItem(SAVE_KEY,JSON.stringify(this.s));this.storageFailed=false;}catch{if(!this.storageFailed)this.notice('Browser storage unavailable. Export your save from Settings.');this.storageFailed=true;}}
 load(){try{const raw=localStorage.getItem(SAVE_KEY);if(raw){this.s=this.validate(JSON.parse(raw));this.offline();}}catch{this.loadError='Your stored save could not be loaded. A fresh session is ready. Use Import to restore a backup.';}}
 import(text){const next=this.validate(JSON.parse(text));try{localStorage.setItem(SAVE_KEY+'-backup',JSON.stringify(this.s));}catch{}this.s=next;this.calendar();this.offline();this.recompute();this.progress();this.emit('world');this.emit('teleport','lab');this.save();}
}
