import * as THREE from 'three';
import {AREAS,MACHINES,SKINS,DRONES} from './data.js';
const V=THREE.Vector3;
/* Fixed orthographic camera. The player manages the map directly; there is no avatar or walking controller. */
export class World{
 constructor(state,canvas){this.state=state;this.canvas=canvas;this.scene=new THREE.Scene();this.scene.background=new THREE.Color('#111a22');this.camera=new THREE.OrthographicCamera(-20,20,15,-15,.1,220);this.renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));this.renderer.setSize(innerWidth,innerHeight);this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=.9;this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;this.renderer.shadowMap.autoUpdate=false;
 this.clock=0;this.target=new V(0,0,0);this.goal=new V(0,0,0);this.size=Math.max(42,38/(innerWidth/innerHeight));this.goalSize=this.size;this.player=new V(0,0,0);this.yaw=0;this.goalYaw=0;this.pitch=0;this.paused=true;this.keys={};this.moveStick={x:0,y:0};this.arena=null;this.zone='lab';this.current=null;this.pointer={x:innerWidth/2,y:innerHeight/2,inside:false};this.ray=new THREE.Raycaster();this.interactables=[];this.areaGroups={};this.plotGroups={};this.machineGroups=[];this.machines=this.machineGroups;this.shards=[];this.animators=[];this.particles=[];this.materials=new Map();this.geometry={box:new THREE.BoxGeometry(1,1,1),sphere:new THREE.SphereGeometry(1,16,12),cylinder:new THREE.CylinderGeometry(1,1,1,16),torus:new THREE.TorusGeometry(1,.05,6,40)};
 this.scene.add(new THREE.HemisphereLight('#a4c9ec','#293a42',2.2));this.sun=new THREE.DirectionalLight('#d9e9ff',2.5);this.sun.position.set(-15,32,20);this.sun.castShadow=true;this.sun.shadow.mapSize.set(2048,2048);Object.assign(this.sun.shadow.camera,{left:-80,right:80,top:60,bottom:-60,near:1,far:120});this.sun.shadow.normalBias=.04;this.scene.add(this.sun);
 this.floorMat=this.grassMaterial();const ground=this.box(this.scene,0,-.7,0,210,.2,200,'#b8cd91');ground.material=this.floorMat;
 this.buildFacility();this.buildManagement();this.buildArenas();this.droneGroup=new THREE.Group();this.scene.add(this.droneGroup);
 this.hoverRing=new THREE.Mesh(new THREE.RingGeometry(1.3,1.4,48),new THREE.MeshBasicMaterial({color:'#fffbe1',transparent:true,opacity:.9,side:THREE.DoubleSide,depthWrite:false}));this.hoverRing.rotation.x=-Math.PI/2;this.hoverRing.visible=false;this.scene.add(this.hoverRing);
 this.input();this.sync();this.applySettings();this.resize();window.addEventListener('resize',()=>this.resize());state.on(type=>{if(['world','area','machine','collected','skill'].includes(type))this.sync();});}
 mat(color,glow=false){const key=color+glow;if(!this.materials.has(key))this.materials.set(key,new THREE.MeshStandardMaterial({color,roughness:.85,metalness:.03,emissive:glow?color:'#000000',emissiveIntensity:glow?.18:0}));return this.materials.get(key);}
 box(g,x,y,z,w,h,d,color,glow=false){const m=new THREE.Mesh(this.geometry.box,this.mat(color,glow));m.position.set(x,y,z);m.scale.set(w,h,d);m.castShadow=!glow&&h>.2;m.receiveShadow=true;g.add(m);return m;}
 sphere(g,x,y,z,r,color,glow=false){const m=new THREE.Mesh(this.geometry.sphere,this.mat(color,glow));m.position.set(x,y,z);m.scale.setScalar(r);m.castShadow=!glow;g.add(m);return m;}
 cylinder(g,x,y,z,r,h,color){const m=new THREE.Mesh(this.geometry.cylinder,this.mat(color));m.position.set(x,y,z);m.scale.set(r,h,r);m.castShadow=true;m.receiveShadow=true;g.add(m);return m;}
 ring(g,x,y,z,r,color,rx=Math.PI/2){const m=new THREE.Mesh(this.geometry.torus,this.mat(color,true));m.position.set(x,y,z);m.scale.setScalar(r);m.rotation.x=rx;g.add(m);return m;}
 grassMaterial(){const c=document.createElement('canvas');c.width=c.height=128;const ctx=c.getContext('2d');ctx.fillStyle='#26373c';ctx.fillRect(0,0,128,128);let seed=624;const rand=()=>{seed=(seed*16807)%2147483647;return seed/2147483647;};for(let i=0;i<900;i++){ctx.fillStyle=['#293b40','#2c3e42','#24343a','#2a3b3d'][i%4];ctx.fillRect(Math.floor(rand()*128),Math.floor(rand()*128),2,2);}const tex=new THREE.CanvasTexture(c);tex.colorSpace=THREE.SRGBColorSpace;tex.wrapS=tex.wrapT=THREE.RepeatWrapping;tex.repeat.set(25,25);return new THREE.MeshStandardMaterial({map:tex,roughness:1});}
 label(g,text,x,y,z,width=4,color='#244638'){const c=document.createElement('canvas');c.width=512;c.height=128;const ctx=c.getContext('2d');ctx.fillStyle='#151c24';ctx.beginPath();ctx.roundRect(10,20,492,86,15);ctx.fill();ctx.strokeStyle='#3a4a57';ctx.lineWidth=3;ctx.stroke();ctx.font='600 40px Arial';ctx.textAlign='center';ctx.fillStyle='#c8d9e6';if(ctx.measureText(text).width>465)ctx.font='600 '+Math.floor(40*465/ctx.measureText(text).width)+'px Arial';ctx.fillText(text,256,77);const tex=new THREE.CanvasTexture(c);tex.colorSpace=THREE.SRGBColorSpace;const m=new THREE.Sprite(new THREE.SpriteMaterial({map:tex,depthWrite:false}));m.position.set(x,y,z);m.scale.set(width,width*128/512,1);g.add(m);return m;}
 bind(obj,action,data,label,range=Infinity){const record={obj,action,data,label,range};obj.traverse(o=>{if(o.isMesh)o.userData.interactable=record;});this.interactables.push(obj);return record;}
 house(parent,x,z,title,action,color='#bf6e46',w=4.5,d=3.6){const g=new THREE.Group();g.position.set(x,0,z);parent.add(g);this.box(g,0,.18,0,w+.4,.35,d+.4,'#ac9670');this.box(g,0,1.2,0,w,2.1,d,'#ead9b0');this.box(g,0,.45,d/2+.25,1.1,.5,.6,'#bc9561');this.box(g,0,1,d/2+.02,.8,1.5,.06,'#796246');for(const wx of [-1.45,1.45]){this.box(g,wx,1.35,d/2+.03,.85,.9,.08,'#f6edcd');this.box(g,wx,1.35,d/2+.1,.65,.7,.05,'#70a7ae');this.box(g,wx,1.35,d/2+.14,.05,.74,.03,'#eadfbc');}for(const side of [-1,1]){const roof=this.box(g,side*w*.25,2.65,0,w*.57,.18,d+.6,color);roof.rotation.z=side*-.40;for(let j=0;j<5;j++){const ridge=this.box(g,side*w*.25,2.76,-d/2+j*d/4,w*.58,.04,.045,'#a65d3c');ridge.rotation.z=side*-.40;}}this.box(g,w*.3,3.1,-d*.2,.5,1,.6,'#bb9971');this.label(g,title,0,3.65,0,w+1);this.bind(g,action,null,title);return g;}
 tree(parent,x,z,scale=1,tint='#568653'){const g=new THREE.Group();g.position.set(x,0,z);g.scale.setScalar(scale);parent.add(g);this.cylinder(g,0,.75,0,.15,1.5,'#96714d');this.sphere(g,0,1.65,0,.8,tint);this.sphere(g,-.3,1.35,.2,.62,'#69974f');this.sphere(g,.35,1.4,-.2,.62,'#73a358');return g;}
 flowerbed(g,x,z,w=2.8,d=2){this.box(g,x,.05,z,w,.12,d,'#aa865c');for(let row=0;row<3;row++)for(let col=0;col<4;col++){const px=x-w*.36+col*w*.24,pz=z-d*.32+row*d*.32;this.sphere(g,px,.22,pz,.13,'#527c43');if((row+col)%3===0)this.sphere(g,px,.4,pz,.1,'#e8bd65');}}
 fence(g){for(const z of [-10.5,10.5])for(let x=-10;x<=10;x+=2){if(Math.abs(x)<3)continue;this.box(g,x,.55,z,.16,1.1,.16,'#bd9462');this.box(g,x,.65,z,2,.12,.12,'#caab7c');this.box(g,x,.3,z,2,.12,.12,'#caab7c');}for(const x of [-10.5,10.5])for(let z=-10;z<=10;z+=2){if(Math.abs(z)<3)continue;this.box(g,x,.55,z,.16,1.1,.16,'#bd9462');this.box(g,x,.65,z,.12,.12,2,'#caab7c');this.box(g,x,.3,z,.12,.12,2,'#caab7c');}}
 buildFacility(){for(const a of AREAS){const base=new THREE.Group();base.position.set(a.x,0,a.z);this.scene.add(base);this.plotGroups[a.id]=base;this.box(base,0,-.3,0,22,.5,22,'#8db471');const dirt=this.box(base,0,-.025,0,22,.06,2.5,'#d7bc86');this.box(base,0,-.02,0,2.5,.06,22,'#d7bc86');if(a.id!=='lab')this.fence(base);const g=new THREE.Group();base.add(g);this.areaGroups[a.id]=g;
 const sealed=new THREE.Group();base.add(sealed);this.box(sealed,0,.01,0,12,.06,9,'#b2bc91');const sign=this.label(sealed,a.name.toUpperCase(),0,1.1,0,8,'#687257');this.label(sealed,'EXPAND TO UNLOCK',0,.5,3,5,'#778061');this.bind(sealed,'locked',a.id,a.name+' · expand to unlock');base.userData.sealed=sealed;
 for(const [x,z,t]of [[-9,-8,1.1],[9,-9,.9],[-9,8,.85],[9,8,1.05]])this.tree(base,x,z,t,a.id==='dimension'?'#8c84a6':a.id==='planet'?'#638d68':'#58884e');
 if(a.id!=='lab'){const building=this.house(g,-5,-4,a.name,a.id==='research'?'research':a.id==='quantum'||a.id==='dimension'?'rebirth':a.id==='factory'?'drones':a.id==='deep'?'challenges':'travel',['#bf7750','#6688a0','#9a869f'][AREAS.indexOf(a)%3],5,4);this.flowerbed(g,-6,5,4,3);this.flowerbed(g,6,5,4,3);}
 }
 for(const a of AREAS)for(const b of AREAS)if(b.x===a.x+28&&b.z===a.z||b.z===a.z+28&&b.x===a.x){const x=(a.x+b.x)/2,z=(a.z+b.z)/2;this.box(this.scene,x,-.03,z,a.x===b.x?2.5:6,.12,a.z===b.z?2.5:6,'#d7bc86');}
 const lab=this.areaGroups.lab;this.house(lab,-6,-5,'Skill workshop','tree','#b56c45',4.8,4);this.house(lab,-6,5,'Daily supplies','daily','#899d71',3.5,3);
 this.house(lab,6,5,'Arcade','arcade','#788fa3',3.8,3.3);this.flowerbed(lab,-5,0,3,2);this.flowerbed(lab,5,0,3,2);
 this.core=new THREE.Group();this.core.position.set(0,0,-2);lab.add(this.core);this.box(lab,0,.03,-2,5.5,.1,5.5,'#d7c797');this.cylinder(this.core,0,.2,0,1.7,.4,'#aaa98d');this.cylinder(this.core,0,.55,0,1.3,.3,'#ece2c5');this.ring(this.core,0,.75,0,1.15,'#67afac');this.coreSphere=this.sphere(this.core,0,1.65,0,.82,'#78d1cd',true);this.coreRings=[];for(let i=0;i<4;i++){const r=this.ring(this.core,0,1.65,0,1.1+i*.12,'#80bbac',i*.6);this.coreRings.push(r);}this.bind(this.core,'core',null,'Energy core');this.label(this.core,'Energy core',0,3.3,0,4.3);
 const chief=this.person('#d8ba77');chief.position.set(-3,0,5);lab.add(chief);this.bind(chief,'npc','engineer','Chief engineer');this.label(chief,'Engineer',0,1.5,0,2.5);this.npcs=[chief];
 MACHINES.forEach((d,i)=>{const a=AREAS.find(a=>a.id===d.area),g=new THREE.Group();g.position.set(6,0,-5);this.areaGroups[a.id].add(g);const base=this.box(g,0,.12,0,4.4,.25,4.4,'#a7a38a');this.box(g,0,.3,0,3.8,.12,3.8,'#d0c5a3');const built=new THREE.Group();g.add(built);this.box(built,0,.95,0,1.4,1.3,1.4,'#708e8a');this.cylinder(built,0,1.8,0,.55,.5,'#d8ddc2');const rotor=this.ring(built,0,2.05,0,.66,'#73b9ae');this.sphere(built,0,2.12,0,.28,'#b6dfc6',true);for(const x of [-1.4,1.4]){const panel=this.box(built,x,.65,.2,.95,.12,2.5,'#426e80');panel.rotation.z=x<0?.22:-.22;for(let j=0;j<5;j++)this.box(built,x,.73,-.8+j*.48,.9,.015,.03,'#91b4bb');}const upgrades=new THREE.Group();built.add(upgrades);for(const x of [-1.2,1.2])this.cylinder(upgrades,x,.8,-1.3,.3,1.5,'#b8b28e');const scaffold=new THREE.Group();g.add(scaffold);for(const x of [-1.4,1.4])for(const z of [-1.4,1.4])this.box(scaffold,x,.6,z,.18,1.2,.18,'#b3986c');this.label(scaffold,'BUILD',0,1.2,0,2.5,'#6f7b5c');this.label(g,d.name,0,3.5,0,5.8);g.userData={built,scaffold,upgrades,rotor};this.bind(g,'machine',i,d.name);this.machineGroups.push(g);});
 for(const [area,id,x,z]of [['research','scientist',0,5],['factory','technician',-4,3],['launch','explorer',-3,4]]){const p=this.person('#a0b4bc');p.position.set(x,0,z);this.areaGroups[area].add(p);this.bind(p,'npc',id,id.charAt(0).toUpperCase()+id.slice(1));this.npcs.push(p);}
 this.secretObject(this.areaGroups.lab,-9,4,'tunnel');this.secretObject(this.areaGroups.deep,-8,-7,'terminal');this.secretObject(this.areaGroups.dimension,4,7,'hidden');
 AREAS.forEach((a,ai)=>{for(let j=0;j<5;j++){const coords=[[-8,-2],[8,3],[-8,7],[3,-8],[-3,-7]][j];const m=new THREE.Mesh(new THREE.OctahedronGeometry(.25),this.mat('#e3c276',true));m.position.set(a.x+coords[0],.5,a.z+coords[1]);this.scene.add(m);m.userData.shard=ai*5+j;this.shards.push(m);this.bind(m,'shard',ai*5+j,'Collect energy shard');}});
 }
 secretObject(parent,x,z,id){const box=this.box(parent,x,.25,z,.8,.5,.8,'#b99773');this.bind(box,'secret',id,'Inspect hidden supply');}
 person(color){const g=new THREE.Group();this.cylinder(g,0,.4,0,.18,.65,color);this.sphere(g,0,.9,0,.22,'#e0c49c');this.cylinder(g,0,1.08,0,.28,.10,'#b19a70');return g;}
 buildArenas(){this.arenaRoots={};for(const [id,x,z]of [['target',0,70],['memory',34,70],['catch',68,70],['parkour',108,70],['boss',-34,70]]){const g=new THREE.Group();g.position.set(x,0,z);this.scene.add(g);this.arenaRoots[id]=g;this.box(g,0,-.2,0,22,.4,20,'#c8c4a1');this.box(g,0,.02,0,20,.06,18,'#e4d4aa');for(const v of [-10.5,10.5])this.box(g,v,.35,0,.18,.7,20,'#9aaf87');this.label(g,id==='parkour'?'Reactor relay':id==='memory'?'Reactor stabilisation':id==='target'?'Target garden':id==='catch'?'Crystal catch':'Boss arena',0,.7,-8,9);g.visible=false;}
 this.catchTray=new THREE.Group();this.box(this.catchTray,0,.15,0,2,.25,1.5,'#638d7d');this.box(this.catchTray,0,.35,-.7,2,.3,.15,'#b7ceb0');this.arenaRoots.catch.add(this.catchTray);this.parkourPlatforms=[];
 }
 sync(){const s=this.state.s;for(const a of AREAS){const open=s.areas.includes(a.id);this.areaGroups[a.id].visible=open;this.plotGroups[a.id].userData.sealed.visible=!open;this.plotGroups[a.id].children[0].material=this.mat(open?'#97ba77':'#b9c59e');}this.machineGroups.forEach((g,i)=>{const l=s.machines[i];g.userData.built.visible=l>0;g.userData.scaffold.visible=!l;g.userData.upgrades.visible=l>=10;g.userData.level=l;g.userData.built.scale.setScalar(1+Math.min(.28,Math.log10(l+1)*.1));});this.shards.forEach((m,i)=>m.visible=!s.collected.includes(i)&&s.areas.includes(AREAS[Math.floor(i/5)].id));const skin=SKINS.find(d=>d[0]===s.skin);this.coreSphere.material=this.mat(skin[2],true);this.coreRings.forEach((r,i)=>r.visible=i<2+Math.min(2,Math.floor(Math.log10(Math.max(1,s.lifetime))/3)));this.droneSync();this.renderer.shadowMap.needsUpdate=true;}
 droneSync(){const key=this.state.s.equipped.join(',');if(this.droneKey===key)return;this.droneKey=key;this.droneGroup.clear();for(const i of this.state.s.equipped){const g=new THREE.Group();this.droneGroup.add(g);this.sphere(g,0,0,0,.2,DRONES[i][2]);this.ring(g,0,0,0,.35,DRONES[i][2]);}}
 applySettings(){const s=this.state.s.settings;this.renderer.setPixelRatio(Math.min(devicePixelRatio,{low:.8,medium:1,high:1.5,ultra:2}[s.quality]));this.renderer.shadowMap.enabled=s.shadows&&s.quality!=='low';this.renderer.shadowMap.needsUpdate=true;this.sun.intensity=s.lighting?2.1:1.5;this.machineGroups.forEach(g=>g.userData.built.children[0].material=this.mat(s.machineColor));this.resize();}
 resize(){const aspect=innerWidth/innerHeight;this.camera.left=-this.size*aspect/2;this.camera.right=this.size*aspect/2;this.camera.top=this.size/2;this.camera.bottom=-this.size/2;this.camera.updateProjectionMatrix();this.renderer.setSize(innerWidth,innerHeight);}
 frame(){const aspect=innerWidth/innerHeight;this.camera.left=-this.size*aspect/2;this.camera.right=this.size*aspect/2;this.camera.top=this.size/2;this.camera.bottom=-this.size/2;this.camera.updateProjectionMatrix();this.camera.position.copy(this.target).add(new V(Math.sin(this.yaw)*32,46,Math.cos(this.yaw)*32));this.camera.lookAt(this.target);this.camera.updateMatrixWorld();}
 input(){let drag=null;const touches=new Map();let pinch=null;const updatePointer=e=>{this.pointer.x=e.clientX;this.pointer.y=e.clientY;this.pointer.inside=true;};this.canvas.addEventListener('pointerdown',e=>{if(this.paused)return;updatePointer(e);touches.set(e.pointerId,{x:e.clientX,y:e.clientY});this.canvas.setPointerCapture(e.pointerId);if(touches.size===2){const [a,b]=[...touches.values()];pinch={distance:Math.hypot(a.x-b.x,a.y-b.y),size:this.goalSize};drag=null;return;}drag={id:e.pointerId,x:e.clientX,y:e.clientY,gx:this.goal.x,gz:this.goal.z,yaw:this.goalYaw,moved:false,button:e.button};});this.canvas.addEventListener('pointermove',e=>{updatePointer(e);if(touches.has(e.pointerId))touches.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pinch&&touches.size===2){const [a,b]=[...touches.values()];this.goalSize=Math.max(17,Math.min(100,pinch.size*pinch.distance/Math.max(10,Math.hypot(a.x-b.x,a.y-b.y))));return;}if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.hypot(dx,dy)>6)drag.moved=true;if(drag.moved&&!this.arena){if(drag.button===2){this.goalYaw=drag.yaw-dx*.006*this.state.s.settings.sensitivity;return;}const factor=this.size/innerHeight,cy=Math.cos(this.yaw),sy=Math.sin(this.yaw);this.goal.x=Math.max(-75,Math.min(75,drag.gx-(dx*cy+dy*sy*1.26)*factor));this.goal.z=Math.max(-55,Math.min(25,drag.gz+(dx*sy-dy*cy*1.26)*factor));}});this.canvas.addEventListener('pointerup',e=>{touches.delete(e.pointerId);if(pinch){pinch=null;drag=null;return;}if(drag&&drag.id===e.pointerId&&!drag.moved&&drag.button===0){this.pick();if(this.current)this.interact();else this.state.emit('groundclick',this.groundPointer());}drag=null;});this.canvas.addEventListener('pointercancel',()=>{drag=null;pinch=null;touches.clear();});this.canvas.addEventListener('pointerleave',()=>{if(!drag)this.pointer.inside=false;});this.canvas.addEventListener('wheel',e=>{if(this.paused)return;e.preventDefault();this.zoom(e.deltaY>0?1.1:1/1.1);},{passive:false});this.canvas.addEventListener('contextmenu',e=>e.preventDefault());document.addEventListener('keydown',e=>{if(/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;this.keys[e.code]=true;if(e.code==='Home'&&!this.paused)this.teleport('lab');});document.addEventListener('keyup',e=>this.keys[e.code]=false);window.addEventListener('blur',()=>this.keys={});}
 zoom(factor){this.goalSize=Math.max(17,Math.min(100,this.goalSize*factor));}
 overview(){this.arena=null;this.goal.set(0,0,-14);this.goalSize=Math.max(59,130/(innerWidth/innerHeight));this.toggleArenas();}
 home(){this.teleport(this.zone||'lab');}
 teleport(id){const a=AREAS.find(a=>a.id===id);if(a){this.arena=null;this.zone=id;this.goal.set(a.x,0,a.z);this.player.set(a.x,0,a.z);this.goalSize=Math.max(42,38/(innerWidth/innerHeight));}else if(this.arenaRoots[id]){this.arena=id;this.goal.copy(this.arenaRoots[id].position);this.goalSize=Math.max(id==='parkour'?31:28,25/(innerWidth/innerHeight));this.player.copy(this.goal);}this.goalYaw=0;this.frame();this.toggleArenas();this.current=null;this.keys={};this.state.emit('zone',a?a.name:id==='parkour'?'Reactor relay':id.charAt(0).toUpperCase()+id.slice(1));}
 toggleArenas(){for(const [id,g]of Object.entries(this.arenaRoots))g.visible=this.arena===id;this.renderer.shadowMap.needsUpdate=true;}
 allowed(){return true;}
 groundPointer(){this.ray.setFromCamera(new THREE.Vector2(this.pointer.x/innerWidth*2-1,-this.pointer.y/innerHeight*2+1),this.camera);const p=new V();return this.ray.ray.intersectPlane(new THREE.Plane(new V(0,1,0),0),p)?p:null;}
 pick(){this.current=null;if(!this.pointer.inside||this.paused)return;this.ray.setFromCamera(new THREE.Vector2(this.pointer.x/innerWidth*2-1,-this.pointer.y/innerHeight*2+1),this.camera);for(const hit of this.ray.intersectObjects(this.interactables,true)){let visible=true,p=hit.object;while(p){if(!p.visible)visible=false;p=p.parent;}if(!visible)continue;const r=hit.object.userData.interactable;if(r){if(this.arena&&!['target','memory','boss','shield','relay','event'].includes(r.action))continue;this.current=r;break;}}}
 interact(){if(!this.paused&&this.current)this.state.emit('interact',this.current);}
 addTarget(obj,action,data,label,range=Infinity){this.scene.add(obj);this.bind(obj,action,data,label,range);}
 removeTarget(obj){this.scene.remove(obj);const i=this.interactables.indexOf(obj);if(i>=0)this.interactables.splice(i,1);}
 pulse(){this.corePulse=.16;this.burst(new V(0,1.8,-2),'#91d8bc',8);}
 burst(pos,color,count=10){if(!this.state.s.settings.particles||this.state.s.settings.reduced)return;for(let i=0;i<count&&this.particles.length<70;i++){const m=new THREE.Mesh(this.geometry.sphere,this.mat(color));m.position.copy(pos);m.scale.setScalar(.05);this.scene.add(m);this.particles.push({m,v:new V((Math.random()-.5)*3,Math.random()*3,(Math.random()-.5)*3),life:.65});}}
 update(dt){this.clock+=dt;const reduced=this.state.s.settings.reduced;if(!this.paused&&!this.arena){const speed=dt*this.size*.6;const x=Number(!!(this.keys.ArrowRight||this.keys.KeyD))-Number(!!(this.keys.ArrowLeft||this.keys.KeyA)),z=Number(!!(this.keys.ArrowDown||this.keys.KeyS))-Number(!!(this.keys.ArrowUp||this.keys.KeyW));this.goal.x=Math.max(-75,Math.min(75,this.goal.x+(x*Math.cos(this.yaw)+z*Math.sin(this.yaw))*speed));this.goal.z=Math.max(-55,Math.min(25,this.goal.z+(z*Math.cos(this.yaw)-x*Math.sin(this.yaw))*speed));}this.yaw+=(this.goalYaw-this.yaw)*(reduced?1:1-Math.exp(-dt*8));this.target.lerp(this.goal,reduced?1:1-Math.exp(-dt*8));this.size+=(this.goalSize-this.size)*(reduced?1:1-Math.exp(-dt*9));this.frame();if(!reduced){this.coreRings.forEach((r,i)=>{r.rotation.y+=dt*(.3+i*.15);r.rotation.z+=dt*.12;});this.coreSphere.position.y=1.65+Math.sin(this.clock*2)*.05;this.machineGroups.forEach(g=>g.userData.rotor.rotation.z+=dt*(.5+Math.log2((g.userData.level||0)+1)*.2));this.shards.forEach(m=>{m.rotation.y+=dt;m.position.y=.5+Math.sin(this.clock*2+m.userData.shard)*.06;});}this.corePulse=Math.max(0,(this.corePulse||0)-dt);this.core.scale.setScalar(1+this.corePulse);this.droneGroup.children.forEach((d,i)=>{const a=this.clock*.6+i*2;d.position.set(this.goal.x+Math.cos(a)*3,2,this.goal.z+Math.sin(a)*3);});this.particles=this.particles.filter(p=>{p.m.position.addScaledVector(p.v,dt);p.life-=dt;if(p.life<=0){this.scene.remove(p.m);return false;}return true;});if(this.arena==='catch'&&!this.paused){const p=this.groundPointer();if(p){this.player.x=Math.max(59,Math.min(77,p.x));this.player.z=Math.max(63,Math.min(77,p.z));this.catchTray.position.set(this.player.x-68,.1,this.player.z-70);}}this.pick();this.hoverRing.visible=!!this.current&&!this.arena;this.canvas.style.cursor=this.current?'pointer':this.arena==='catch'?'crosshair':'grab';if(this.current){const pos=new V();this.current.obj.getWorldPosition(pos);this.hoverRing.position.set(pos.x,.11,pos.z);this.hoverRing.scale.setScalar(this.current.action==='core'?1.55:this.current.action==='machine'?1.8:.8);}this.updateManagement(dt);this.renderer.render(this.scene,this.camera);}
}
