import * as THREE from 'three';
import {EffectComposer} from 'three/addons/postprocessing/EffectComposer.js';
import {RenderPass} from 'three/addons/postprocessing/RenderPass.js';
import {UnrealBloomPass} from 'three/addons/postprocessing/UnrealBloomPass.js';
import {OutputPass} from 'three/addons/postprocessing/OutputPass.js';
import {AREAS,MACHINES,SKINS,OUTFITS,DRONES} from './data.js';
const V=THREE.Vector3;
export class World{
 constructor(state,canvas){this.state=state;this.canvas=canvas;this.scene=new THREE.Scene();this.scene.background=new THREE.Color('#080f18');this.scene.fog=new THREE.FogExp2('#080f18',.010);this.camera=new THREE.PerspectiveCamera(68,innerWidth/innerHeight,.1,250);this.renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));this.renderer.setSize(innerWidth,innerHeight);this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.15;this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;this.composer=new EffectComposer(this.renderer);this.composer.addPass(new RenderPass(this.scene,this.camera));this.bloomPass=new UnrealBloomPass(new THREE.Vector2(innerWidth,innerHeight),.15,.3,1.25);this.composer.addPass(this.bloomPass);this.composer.addPass(new OutputPass());this.clock=0;this.yaw=state.s.position.yaw;this.pitch=state.s.position.pitch;this.player=new V(0,0,7);this.velY=0;this.grounded=true;this.keys={};this.moveStick={x:0,y:0};this.interactables=[];this.colliders=[];this.cameraObstacles=[];this.areaGroups={};this.doors=[];this.animators=[];this.machines=[];this.shards=[];this.particles=[];this.current=null;this.zone='lab';this.arena=null;this.paused=false;this.aim=new THREE.Vector2();this.ray=new THREE.Raycaster();this.shake=0;this.pulseScale=0;this.outfitCache=-1;this.materials=new Map();this.effectGroup=new THREE.Group();this.scene.add(this.effectGroup);this.geometry={box:new THREE.BoxGeometry(1,1,1),sphere:new THREE.SphereGeometry(1,24,16),cylinder:new THREE.CylinderGeometry(1,1,1,12),torus:new THREE.TorusGeometry(1,.035,8,60)};
 this.scene.add(new THREE.HemisphereLight('#c4e1ff','#243449',2));this.sun=new THREE.DirectionalLight('#d1eaff',2.4);this.sun.position.set(15,25,12);this.sun.castShadow=true;this.sun.shadow.mapSize.set(1024,1024);Object.assign(this.sun.shadow.camera,{left:-30,right:30,top:30,bottom:-30,far:100});this.scene.add(this.sun);this.ambient=new THREE.PointLight('#79ddf9',40,18,2);this.ambient.position.set(0,4,0);this.scene.add(this.ambient);this.buildSky();this.buildFacility();this.buildArenas();this.buildAvatar();this.input();this.sync();this.applySettings();window.addEventListener('resize',()=>this.resize());state.on((type)=>{if(['world','area','machine','collected','skill'].includes(type))this.sync();});}
 mat(color,emissive=false,metal=.35){const key=color+'-'+emissive+'-'+metal;if(!this.materials.has(key))this.materials.set(key,new THREE.MeshStandardMaterial({color,roughness:emissive?.35:.65,metalness:metal,emissive:emissive?color:'#000000',emissiveIntensity:emissive?1.8:0}));return this.materials.get(key);}
 box(g,x,y,z,w,h,d,color,glow=false){const m=new THREE.Mesh(this.geometry.box,this.mat(color,glow));m.position.set(x,y,z);m.scale.set(w,h,d);m.castShadow=!glow;m.receiveShadow=true;g.add(m);if(h>.3&&(w>4||h>3||d>4))this.cameraObstacles.push(m);return m;}
 sphere(g,x,y,z,r,color,glow=false){const m=new THREE.Mesh(this.geometry.sphere,this.mat(color,glow));m.position.set(x,y,z);m.scale.setScalar(r);g.add(m);return m;}
 cylinder(g,x,y,z,r,h,color){const m=new THREE.Mesh(this.geometry.cylinder,this.mat(color));m.position.set(x,y,z);m.scale.set(r,h,r);m.castShadow=true;m.receiveShadow=true;g.add(m);return m;}
 ring(g,x,y,z,r,color,rx=Math.PI/2){const m=new THREE.Mesh(this.geometry.torus,this.mat(color,true));m.position.set(x,y,z);m.scale.setScalar(r);m.rotation.x=rx;g.add(m);return m;}
 label(g,text,x,y,z,width=4,color='#bfe4ea'){const c=document.createElement('canvas');c.width=768;c.height=128;const ctx=c.getContext('2d');ctx.clearRect(0,0,768,128);ctx.font='600 32px Arial';ctx.textAlign='center';ctx.fillStyle=color;ctx.fillText(text,384,75);const tex=new THREE.CanvasTexture(c);tex.colorSpace=THREE.SRGBColorSpace;const m=new THREE.Sprite(new THREE.SpriteMaterial({map:tex,transparent:true,depthWrite:false}));m.position.set(x,y,z);m.scale.set(width,width/6,1);g.add(m);return m;}
 sign(g,text,x,z,color='#89dacf'){const c=document.createElement('canvas');c.width=512;c.height=128;const ctx=c.getContext('2d');ctx.font='bold 35px Arial';ctx.textAlign='center';ctx.fillStyle=color;ctx.fillText(text,256,65);ctx.fillRect(100,85,312,3);const tex=new THREE.CanvasTexture(c);tex.colorSpace=THREE.SRGBColorSpace;const p=new THREE.Mesh(new THREE.PlaneGeometry(5,1.25),new THREE.MeshBasicMaterial({map:tex,transparent:true,depthWrite:false}));p.rotation.x=-Math.PI/2;p.position.set(x,.02,z);g.add(p);}
 bind(obj,action,data,label,range=3.5){const record={obj,action,data,label,range};obj.traverse(o=>{if(o.isMesh)o.userData.interactable=record;});this.interactables.push(obj);return record;}
 obstacle(x,z,w,d,y=0,h=3){this.colliders.push({x,z,w,d,y,h});}
 buildSky(){const positions=[];for(let i=0;i<1200;i++){const a=Math.random()*Math.PI*2,r=110+Math.random()*120,y=20+Math.random()*120;positions.push(Math.cos(a)*r,y,Math.sin(a)*r);}const geom=new THREE.BufferGeometry();geom.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));this.stars=new THREE.Points(geom,new THREE.PointsMaterial({color:'#b9d4ec',size:.2,transparent:true,opacity:.8}));this.scene.add(this.stars);const planet=new THREE.Mesh(new THREE.SphereGeometry(24,40,24),this.mat('#344f6e'));planet.position.set(-120,55,-160);this.scene.add(planet);const rings=this.ring(this.scene,-120,55,-160,36,'#495377',1.2);rings.rotation.z=.2;}
 buildFacility(){for(const a of AREAS){const g=new THREE.Group();g.position.set(a.x,0,a.z);this.scene.add(g);this.areaGroups[a.id]=g;const floorColor=a.id==='planet'?'#324139':a.id==='dimension'?'#252438':'#243645';this.box(g,0,-.25,0,22,.5,22,floorColor);for(let n=-10;n<=10;n+=2){this.box(g,n,.008,0,.018,.012,22,'#364f5d');this.box(g,0,.008,n,22,.012,.018,'#364f5d');}for(const x of [-10.3,10.3]){this.box(g,x,.03,0,.065,.03,20,a.color,true);for(const z of [-10.3,10.3]){this.box(g,x,2.4,z,.55,4.8,.55,'#344958');this.box(g,x,2.4,z+.3,.10,3.8,.03,a.color,true);}}
 this.sign(g,a.name.toUpperCase(),0,8,a.color);this.label(g,a.name.toUpperCase(),0,4.6,-10.8,8,a.color);
 for(const [dx,dz]of [[1,0],[-1,0],[0,1],[0,-1]]){const neighbor=AREAS.find(b=>b.x===a.x+dx*28&&b.z===a.z+dz*28);if(dx){if(neighbor){this.box(g,dx*11,2.2,-7,.35,4.4,8,'#1a2b39');this.box(g,dx*11,2.2,7,.35,4.4,8,'#1a2b39');this.box(g,dx*11,4.3,0,.35,.8,6,'#354b5c');}else this.box(g,dx*11,2.2,0,.35,4.4,22,'#1a2b39');}else{if(neighbor){this.box(g,-7,2.2,dz*11,8,4.4,.35,'#1a2b39');this.box(g,7,2.2,dz*11,8,4.4,.35,'#1a2b39');this.box(g,0,4.3,dz*11,6,.8,.35,'#354b5c');}else this.box(g,0,2.2,dz*11,22,4.4,.35,'#1a2b39');}
 if(neighbor&&AREAS.indexOf(a)<AREAS.indexOf(neighbor)){const c=new THREE.Group();c.position.set(a.x+dx*14,0,a.z+dz*14);this.scene.add(c);this.box(c,0,-.2,0,dx?6:5,.4,dx?5:6,'#293e4c');this.box(c,0,.04,0,dx?6:.08,.025,dx?.08:6,a.color,true);const gate=this.box(c,0,2,0,dx?.28:5,4,dx?5:.28,'#263748');const light=this.box(c,dx?.18:0,3,dx?0:.18,dx?.04:3.5,.12,dx?3.5:.04,'#e78b7b',true);const text=this.label(c,'LOCKED / '+neighbor.name.toUpperCase(),0,4.8,0,5,'#f0b1a2');this.doors.push({a:a.id,b:neighbor.id,gate,light,text,group:c});}}
 this.decorateArea(g,a);}
 this.core=new THREE.Group();this.core.position.set(0,0,-1.5);this.areaGroups.lab.add(this.core);this.cylinder(this.core,0,.15,0,2.1,.3,'#486477');this.cylinder(this.core,0,.4,0,1.65,.3,'#263f50');this.ring(this.core,0,.58,0,1.6,'#72d8ee');this.cylinder(this.core,0,.75,0,.8,.35,'#3e5d70');this.coreSphere=this.sphere(this.core,0,2,0,.78,'#72d8ee',true);this.coreRings=[];for(let i=0;i<5;i++){const r=this.ring(this.core,0,2,0,1.15+i*.13,'#72d8ee',i*.6);r.rotation.z=i*.5;this.coreRings.push(r);}this.label(this.core,'N O V A  /  O R I G I N',0,4,0,5);this.bind(this.core,'core',null,'Pulse energy core',4.4);this.obstacle(0,-1.5,3.3,3.3,0,.8);
 for(let i=0;i<4;i++){const angle=i*Math.PI/2;this.box(this.areaGroups.lab,Math.cos(angle)*4,.025,Math.sin(angle)*4-1.5,Math.abs(Math.cos(angle))>.5?4:.08,.03,Math.abs(Math.sin(angle))>.5?4:.08,'#72d8ee',true);}
 this.console(this.areaGroups.lab,-6,-4,'SKILL MATRIX','tree','#79dfc4');this.console(this.areaGroups.lab,6,6,'ARCADE TRANSIT','arcade','#baa3fb');this.console(this.areaGroups.lab,-6,7,'DAILY SUPPLY','daily','#f3cb82');this.npc(this.areaGroups.lab,-6,2,'engineer','#f2c58a');
 MACHINES.forEach((d,i)=>{const a=AREAS.find(a=>a.id===d.area),root=new THREE.Group();root.position.set(a.x+6,0,a.z-4);this.scene.add(root);this.machineModel(root,i);this.machines.push(root);this.bind(root,'machine',i,d.name,4);this.obstacle(a.x+6,a.z-4,2.5,2.5,0,2);});
 this.console(this.areaGroups.research,-6,-4,'RESEARCH TERMINAL','research','#bca5fb');this.console(this.areaGroups.research,-6,4,'CENTRAL CONTROL','control','#7decc0');this.npc(this.areaGroups.research,0,5,'scientist','#aab6f8');this.npc(this.areaGroups.factory,-5,4,'technician','#f4cf88');this.npc(this.areaGroups.launch,-5,4,'explorer','#afdbb6');this.console(this.areaGroups.quantum,-5,0,'QUANTUM REBIRTH','rebirth','#f4b3d6');this.console(this.areaGroups.deep,-6,-4,'CHALLENGE CHAMBER','challenges','#eba586');this.console(this.areaGroups.factory,-6,-4,'DRONE FOUNDRY','drones','#8be4bf');this.console(this.areaGroups.dimension,-5,0,'REALITY ENGINE','rebirth','#ddafff');this.console(this.areaGroups.orbital,-5,0,'ORBITAL TRANSIT','travel','#8cbbfb');
 const vent=this.box(this.areaGroups.lab,-9,.45,-8.5,1.1,.9,.15,'#536b75');this.bind(vent,'secret','tunnel','Inspect maintenance vent',2.2);this.label(this.areaGroups.lab,'SERVICE 07',-9,1.2,-8.5,2);const hidden=this.box(this.areaGroups.deep,8,.6,8,.7,1.2,.6,'#b4f297',true);this.bind(hidden,'secret','terminal','Read a hidden terminal',2.4);const relic=this.sphere(this.areaGroups.dimension,-8,1.2,-8,.35,'#efd9ff',true);this.bind(relic,'secret','hidden','Recover a strange archive',2.5);
 AREAS.forEach((a,ai)=>{for(let j=0;j<5;j++){const coords=[[-8,-6],[8,6],[-8,7],[3,-8],[-3,-7]][j];const m=new THREE.Mesh(new THREE.OctahedronGeometry(.22),this.mat(a.color,true));m.position.set(a.x+coords[0],.65+(j===4?.1:0),a.z+coords[1]);this.scene.add(m);m.userData.shard=ai*5+j;this.shards.push(m);this.bind(m,'shard',ai*5+j,'Collect energy shard',2.2);}});
 }
 decorateArea(g,a){for(let i=0;i<4;i++){const x=-8+i*4.7;this.box(g,x,2,-10.7,2.6,1.25,.13,'#344d5b');this.box(g,x,2,-10.60,2.3,.9,.05,'#214253');for(let j=0;j<3;j++)this.box(g,x-.7+j*.5,1.8+j*.12,-10.55,.22,.06+j*.1,.04,a.color,true);}if(a.id==='factory'){for(let i=0;i<3;i++){this.box(g,-5+i*3,.55,0,2,1,3,'#384d59');const gear=this.ring(g,-5+i*3,1.6,0,.65,a.color,0);this.animators.push({obj:gear,axis:'z',speed:1});}const conveyor=this.box(g,0,.4,5,10,.5,1.3,'#4b626f');for(let i=0;i<5;i++){const box=this.box(g,-4+i*2,.9,5,.6,.6,.6,a.color);this.animators.push({obj:box,kind:'conveyor',offset:i*2});}}
 if(a.id==='launch'){this.cylinder(g,0,1.6,-3,1.1,3.2,'#a5b7c4');const cone=new THREE.Mesh(new THREE.ConeGeometry(1.1,2.1,12),this.mat('#cedee5'));cone.position.set(0,4.2,-3);g.add(cone);this.ring(g,0,.3,-3,2,a.color);}
 if(['quantum','orbital','dimension'].includes(a.id)){const group=new THREE.Group();group.position.set(0,2,-3);g.add(group);for(let i=0;i<3;i++){const r=this.ring(group,0,0,0,1.8+i*.25,a.color,i*.75);this.animators.push({obj:r,axis:'y',speed:.2+i*.1});}this.sphere(group,0,0,0,.6,a.color,true);}
 if(a.id==='planet'){for(const [x,z]of [[-5,-4],[4,4],[-6,6]]){const rock=new THREE.Mesh(new THREE.DodecahedronGeometry(1.4),this.mat('#62755e'));rock.position.set(x,.6,z);rock.scale.y=1.8;g.add(rock);this.sphere(g,x,2.5,z,.4,'#b4ef94',true);}}
 if(a.id==='deep'){for(let i=0;i<3;i++)this.cylinder(g,-5+i*4,1.5,-5,.8,3,'#496376');}
 }
 machineModel(root,i){this.cylinder(root,0,.15,0,1.45,.3,'#344a5a');this.box(root,0,.8,0,1.8,1.3,1.8,'#5d7c91');this.box(root,0,1.05,1,1.2,.7,.06,'#172f3e');const rotor=this.ring(root,0,1.7,0,.7,'#79e5c3');root.userData.rotor=rotor;this.cylinder(root,0,1.8,0,.45,.7,'#2c5665');this.sphere(root,0,2.3,0,.3,'#8af9cf',true);const addons=new THREE.Group();root.add(addons);for(let n=0;n<4;n++){const a=n*Math.PI/2;this.cylinder(addons,Math.cos(a)*1.1,1.1,Math.sin(a)*1.1,.18,2,'#4a6879');this.ring(addons,Math.cos(a)*1.1,1.9,Math.sin(a)*1.1,.2,'#7cdcc4');}root.userData.addons=addons;const plate=this.label(root,MACHINES[i].name.toUpperCase(),0,3.1,0,4);root.userData.label=plate;}
 console(parent,x,z,title,action,color){const g=new THREE.Group();g.position.set(x,0,z);parent.add(g);this.box(g,0,.6,0,1,1.2,.8,'#3d5262');this.box(g,0,1.5,0,1.8,.95,.18,'#294250');const screen=this.box(g,0,1.5,.11,1.5,.72,.02,color,true);this.label(g,title,0,2.35,0,4,color);this.bind(g,action,null,title.toLowerCase(),3.4);this.obstacle(parent.position.x+x,parent.position.z+z,1.5,1);return g;}
 npc(parent,x,z,id,color){const g=this.person(color);g.position.set(x,0,z);parent.add(g);this.label(g,id==='engineer'?'CHIEF ENGINEER':id==='scientist'?'DR. LYRA':id==='technician'?'TECHNICIAN OMI':'EXPLORER VEGA',0,2.55,0,4,color);this.bind(g,'npc',id,'Speak to '+id,3.5);this.animators.push({obj:g,kind:'npc',baseX:x,baseZ:z,offset:x+z});}
 person(color){const g=new THREE.Group();this.box(g,0,1.05,0,.65,.75,.4,color);this.sphere(g,0,1.73,0,.26,'#bfd6de');this.box(g,0,1.75,.24,.4,.14,.08,'#142e43');const legs=[];for(const x of [-.19,.19]){const leg=this.box(g,x,.4,0,.24,.7,.26,'#334959');legs.push(leg);this.box(g,x<0?-.47:.47,1,0,.2,.75,.22,color);}g.userData.legs=legs;return g;}
 buildAvatar(){this.avatar=this.person('#b8cbd7');this.scene.add(this.avatar);this.droneGroup=new THREE.Group();this.scene.add(this.droneGroup);this.workerGroup=new THREE.Group();this.scene.add(this.workerGroup);}
 buildArenas(){this.arenaRoots={};for(const [id,x,z,color]of [['target',0,70,'#78dcf9'],['memory',34,70,'#bfa5fd'],['catch',68,70,'#81eac1'],['boss',-34,70,'#f299aa']]){const g=new THREE.Group();g.position.set(x,0,z);this.scene.add(g);this.arenaRoots[id]=g;this.box(g,0,-.2,0,24,.4,24,'#243747');for(const v of [-12,12]){this.box(g,v,2,0,.3,4,24,'#172b3b');this.box(g,0,2,v,24,4,.3,'#172b3b');this.box(g,v,.1,0,.09,.1,24,color,true);}this.sign(g,(id==='memory'?'STABILISATION':id.toUpperCase())+' CHAMBER',0,9,color);this.console(g,9,8,'RETURN TO FACILITY','return',color);}
 const g=new THREE.Group();g.position.set(108,0,70);this.scene.add(g);this.arenaRoots.parkour=g;this.parkourPlatforms=[];const pts=[[0,0,8,5,5],[0,.5,2.5,3.8,3.8],[3,1,-3,3.4,3.4],[-1,1.5,-8,3.5,3.5],[-4,2,-13,3.2,3.2],[1,2.5,-18,3.5,3.5],[3,3,-23,3.2,3.2],[0,3.5,-28,5,5]];pts.forEach(([x,y,z,w,d],i)=>{const p=this.box(g,x,y-.25,z,w,.5,d,'#385467');this.box(p,0,.55,0,.95,.025,.95,'#78eacb',true);this.parkourPlatforms.push({mesh:p,x:108+x,z:70+z,y,w,d,baseX:108+x,index:i});});this.parkourFinish=this.ring(g,0,5,-28,1.5,'#93ffcf',0);this.label(g,'FINISH',0,6.8,-28,4);for(let i=0;i<3;i++){const beam=this.box(g,0,1.6+i*.9,-5-i*8,7,.1,.1,'#f18b9c',true);this.animators.push({obj:beam,kind:'laser',offset:i});}this.sign(g,'REACTOR PARKOUR',0,9);}
 sync(){const s=this.state.s;for(const a of AREAS)this.areaGroups[a.id].visible=s.areas.includes(a.id);for(const [id,g]of Object.entries(this.arenaRoots))g.visible=this.arena===id;this.doors.forEach(d=>{d.open=s.areas.includes(d.a)&&s.areas.includes(d.b);d.group.visible=s.areas.includes(d.a)||s.areas.includes(d.b);d.light.material=this.mat(d.open?'#80e8ba':'#e99888',true);d.text.visible=!d.open;});this.machines.forEach((m,i)=>{const l=s.machines[i];m.visible=s.areas.includes(MACHINES[i].area);m.scale.setScalar(l?1+Math.min(.65,Math.log10(l+1)*.18):.8);m.userData.addons.visible=l>=10;m.userData.rotor.visible=l>0;m.children[1].material=this.mat(l?s.settings.machineColor:'#334a59');m.userData.level=l;});this.shards.forEach((m,i)=>m.visible=!s.collected.includes(i)&&s.areas.includes(AREAS[Math.floor(i/5)].id));const skin=SKINS.find(d=>d[0]===s.skin);if(this.coreSkin!==skin[0]){if(this.coreSkin)this.coreSphere.material.dispose();this.coreSphere.material=this.mat(skin[2],true).clone();this.coreSphere.material.emissiveIntensity=.35;this.coreSphere.material.roughness=.25;this.coreSkin=skin[0];}const evolution=Math.min(6,Math.floor(Math.log10(Math.max(1,s.lifetime))/2)+s.ascensions);this.coreSphere.scale.setScalar(.78+evolution*.06);this.coreRings.forEach((r,i)=>{r.visible=i<2+evolution;r.material=this.mat(skin[2],true);});this.scene.background.set(s.ascensions?'#100e22':'#080f18');this.scene.fog.color.copy(this.scene.background);this.rebuildDrones();this.rebuildWorkers();}
 clearGroup(g){while(g.children.length)g.remove(g.children[0]);}
 rebuildDrones(){if(!this.droneGroup)return;const key=this.state.s.equipped.join(',')+'-'+this.state.s.droneLevels.join(',');if(key===this.droneKey)return;this.droneKey=key;this.clearGroup(this.droneGroup);this.state.s.equipped.forEach(i=>{const g=new THREE.Group();this.droneGroup.add(g);this.sphere(g,0,0,0,.22,DRONES[i][2]);this.ring(g,0,0,0,.36,DRONES[i][2]);this.sphere(g,0,0,.20,.065,'#e8faff',true);g.userData.i=i;});}
 rebuildWorkers(){if(!this.workerGroup)return;const count=this.state.fx.workers?Math.min(8,2+Math.floor(this.state.s.machines.reduce((a,b)=>a+b,0)/20)):0;if(this.workerGroup.children.length===count)return;this.clearGroup(this.workerGroup);for(let i=0;i<count;i++){const bot=this.person('#8ba6ae');bot.scale.setScalar(.65);this.workerGroup.add(bot);}}
 applySettings(){const s=this.state.s.settings,ratios={low:.75,medium:1,high:1.5,ultra:2};this.renderer.setPixelRatio(Math.min(devicePixelRatio,ratios[s.quality]));this.composer.setPixelRatio(Math.min(devicePixelRatio,ratios[s.quality]));this.renderer.shadowMap.enabled=s.shadows&&s.quality!=='low';this.camera.far=s.renderDistance;this.camera.updateProjectionMatrix();this.scene.fog.density=s.quality==='low'?.016:.009;this.ambient.visible=s.lighting;this.sun.intensity=s.lighting?2.4:1.5;this.stars.visible=s.quality!=='low';for(const mat of this.materials.values())if(mat.emissive.getHex())mat.emissiveIntensity=s.bloom?1.8:.7;}
 resize(){this.camera.aspect=innerWidth/innerHeight;this.camera.updateProjectionMatrix();this.renderer.setSize(innerWidth,innerHeight);this.composer.setSize(innerWidth,innerHeight);}
 input(){const look=(dx,dy)=>{if(this.paused)return;this.yaw-=dx*.0024*this.state.s.settings.sensitivity;this.pitch=Math.max(-1.35,Math.min(1.35,this.pitch-dy*.0024*this.state.s.settings.sensitivity));};let drag=false,lastX=0,lastY=0;document.addEventListener('keydown',e=>{if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;this.keys[e.code]=true;if(['Space','Tab','KeyT','KeyE'].includes(e.code)&&!this.paused)e.preventDefault();if(e.code==='KeyE'&&!e.repeat&&!this.paused)this.interact();});document.addEventListener('keyup',e=>this.keys[e.code]=false);window.addEventListener('blur',()=>this.keys={});document.addEventListener('mousemove',e=>{if(document.pointerLockElement===this.canvas)look(e.movementX,e.movementY);else if(drag){look(e.clientX-lastX,e.clientY-lastY);lastX=e.clientX;lastY=e.clientY;}});this.canvas.addEventListener('pointerdown',e=>{if(this.paused)return;if(e.pointerType==='touch'){drag=true;lastX=e.clientX;lastY=e.clientY;this.canvas.setPointerCapture(e.pointerId);return;}if(document.pointerLockElement===this.canvas){if(e.button===0)this.interact();}else if(e.button===2){drag=true;lastX=e.clientX;lastY=e.clientY;}else{this.canvas.requestPointerLock?.()?.catch?.(()=>this.state.notice('Mouse capture unavailable. Hold right mouse to look; use E to interact.'));}});this.canvas.addEventListener('pointermove',e=>{if(e.pointerType==='touch'&&drag){look(e.clientX-lastX,e.clientY-lastY);lastX=e.clientX;lastY=e.clientY;}});window.addEventListener('pointerup',()=>drag=false);this.canvas.addEventListener('contextmenu',e=>e.preventDefault());}
 interact(){if(this.paused)return;if(this.current)this.state.emit('interact',this.current);else if(this.arena==='target'||this.arena==='memory'||this.arena==='boss')this.state.emit('emptyshot');}
 allowed(x,z){if(this.arena==='parkour')return Math.abs(x-108)<15&&z>32&&z<85;if(this.arena){const g=this.arenaRoots[this.arena];return Math.abs(x-g.position.x)<11.5&&Math.abs(z-g.position.z)<11.5;}for(const a of AREAS){if(this.state.s.areas.includes(a.id)&&Math.abs(x-a.x)<10.6&&Math.abs(z-a.z)<10.6)return true;}for(const d of this.doors){if(!d.open)continue;const a=AREAS.find(a=>a.id===d.a),b=AREAS.find(a=>a.id===d.b);if(a.x!==b.x&&Math.abs(z-a.z)<2.5&&x>Math.min(a.x,b.x)+9&&x<Math.max(a.x,b.x)-9)return true;if(a.z!==b.z&&Math.abs(x-a.x)<2.5&&z>Math.min(a.z,b.z)+9&&z<Math.max(a.z,b.z)-9)return true;}return false;}
 canMove(x,z){if(!this.allowed(x,z))return false;if(this.arena)return true;return !this.colliders.some(c=>this.player.y<c.y+c.h-.12&&this.player.y+1.7>c.y&&Math.abs(x-c.x)<c.w/2+.25&&Math.abs(z-c.z)<c.d/2+.25);}
 floorAt(x,z,oldY){if(this.arena==='parkour'){let height=-30;for(const p of this.parkourPlatforms)if(!p.disabled&&Math.abs(x-p.x)<p.w/2+.15&&Math.abs(z-p.z)<p.d/2+.15&&oldY>=p.y-.18)height=Math.max(height,p.y);return height;}let floor=0;if(!this.arena)for(const c of this.colliders)if(c.h<1&&Math.abs(x-c.x)<c.w/2&&Math.abs(z-c.z)<c.d/2&&oldY>=c.h-.15)floor=Math.max(floor,c.h);return floor;}
 teleport(id){const a=AREAS.find(a=>a.id===id);if(a){this.arena=null;this.zone=id;this.player.set(a.x,0,a.z+7);this.yaw=0;this.pitch=0;}else if(this.arenaRoots[id]){this.arena=id;this.player.copy(this.arenaRoots[id].position).add(new V(0,0,id==='parkour'?8:7));this.yaw=0;this.pitch=0;}this.velY=0;this.current=null;this.keys={};for(const [key,g]of Object.entries(this.arenaRoots))g.visible=this.arena===key;this.state.emit('zone',a?a.name:id==='parkour'?'Reactor Parkour':id.charAt(0).toUpperCase()+id.slice(1)+' Chamber');}
 pulse(critical){this.pulseScale=.22;this.shake=critical?.09:.025;const color=SKINS.find(d=>d[0]===this.state.s.skin)[2];this.burst(new V(0,2,-1.5),color,critical?22:10);}
 burst(pos,color,count=10){if(!this.state.s.settings.particles||this.state.s.settings.reduced)return;for(let i=0;i<count&&this.particles.length<120;i++){const m=new THREE.Mesh(this.geometry.sphere,this.mat(color,true));m.scale.setScalar(.035+Math.random()*.045);m.position.copy(pos);this.effectGroup.add(m);this.particles.push({m,v:new V((Math.random()-.5)*5,Math.random()*4,(Math.random()-.5)*5),life:.7});}}
 addTarget(obj,action,data,label,range=60){this.scene.add(obj);this.bind(obj,action,data,label,range);}
 removeTarget(obj){this.scene.remove(obj);const i=this.interactables.indexOf(obj);if(i>=0)this.interactables.splice(i,1);}
 pick(){this.ray.setFromCamera(this.aim,this.camera);const hits=this.ray.intersectObjects(this.interactables,true);this.current=null;for(const hit of hits){let visible=true,p=hit.object;while(p){if(!p.visible)visible=false;p=p.parent;}if(!visible)continue;const r=hit.object.userData.interactable;if(!r)continue;const pos=new V();r.obj.getWorldPosition(pos);const dist=this.player.distanceTo(pos);if(dist<=r.range){this.current=r;break;}}
 }
 update(dt){const settings=this.state.s.settings;this.clock+=dt;const motion=!settings.reduced;this.doors.forEach(d=>d.gate.position.y+=(d.open?6:2)-d.gate.position.y>0?Math.min(((d.open?6:2)-d.gate.position.y),dt*5):Math.max(((d.open?6:2)-d.gate.position.y),-dt*5));
 if(!this.paused){let f=(this.keys.KeyW||this.keys.ArrowUp?1:0)-(this.keys.KeyS||this.keys.ArrowDown?1:0)-this.moveStick.y,r=(this.keys.KeyD?1:0)-(this.keys.KeyA?1:0)+this.moveStick.x;const len=Math.hypot(f,r);if(len>1){f/=len;r/=len;}const sprint=this.keys.ShiftLeft||this.keys.ShiftRight,speed=(sprint?7:4)*(this.keys.KeyC?.6:1);const dx=(-Math.sin(this.yaw)*f+Math.cos(this.yaw)*r)*speed*dt,dz=(-Math.cos(this.yaw)*f-Math.sin(this.yaw)*r)*speed*dt;if(this.canMove(this.player.x+dx,this.player.z))this.player.x+=dx;if(this.canMove(this.player.x,this.player.z+dz))this.player.z+=dz;if(this.keys.Space&&this.grounded){this.velY=7;this.grounded=false;}const oldY=this.player.y;this.velY-=18*dt;this.player.y+=this.velY*dt;const floor=this.floorAt(this.player.x,this.player.z,oldY);if(this.player.y<=floor){this.player.y=floor;this.velY=0;this.grounded=true;}else this.grounded=false;if(this.player.y<-10){this.teleport('parkour');this.state.emit('fall');}if(!this.arena&&this.player.y>.65&&Math.hypot(this.player.x,this.player.z+1.5)<1.7)this.state.secret('reactortop');this.walking=len>.05;this.sprinting=sprint&&this.walking;
 }
 this.avatar.position.copy(this.player);this.avatar.rotation.y=this.yaw+Math.PI;this.avatar.visible=settings.view==='third';this.avatar.userData.legs.forEach((l,i)=>l.rotation.x=this.walking&&motion?Math.sin(this.clock*10+i*Math.PI)*.5:0);const colors=['#cadce1','#d4a875','#83aaa9','#eed36c','#d2e2ea','#aaa0e4','#74638c','#e4c16f'];if(this.outfitCache!==this.state.s.outfit){this.outfitCache=this.state.s.outfit;this.avatar.children[0].material=this.mat(colors[this.outfitCache]);}
 const height=this.keys.KeyC?1.1:1.65,bob=motion&&settings.bob&&this.walking&&this.grounded?Math.sin(this.clock*(this.sprinting?14:10))*.035:0;const eye=new V(this.player.x,this.player.y+height+bob,this.player.z);this.camera.rotation.order='YXZ';this.camera.rotation.set(this.pitch,this.yaw,0);if(settings.view==='third'){const offset=new V(0,1,4.4).applyAxisAngle(new V(0,1,0),this.yaw);const target=eye.clone().add(offset),direction=offset.clone().normalize();const cameraRay=new THREE.Raycaster(eye,direction,.05,offset.length());const blocking=cameraRay.intersectObjects(this.cameraObstacles,false).find(hit=>{let o=hit.object;while(o){if(!o.visible)return false;o=o.parent;}return true;});if(blocking)target.copy(eye).addScaledVector(direction,Math.max(.2,blocking.distance-.25));this.camera.position.lerp(target,1-Math.exp(-dt*14));this.camera.lookAt(eye.clone().add(new V(-Math.sin(this.yaw)*3,this.pitch*4,-Math.cos(this.yaw)*3)));}else this.camera.position.copy(eye);const fov=this.sprinting&&motion?74:68;this.camera.fov+=(fov-this.camera.fov)*Math.min(1,dt*6);this.camera.updateProjectionMatrix();if(settings.shake&&motion&&this.shake>0){this.camera.position.x+=(Math.random()-.5)*this.shake;this.camera.position.y+=(Math.random()-.5)*this.shake;}this.shake=Math.max(0,this.shake-dt*.18);
 if(motion){this.coreRings.forEach((r,i)=>{r.rotation.y+=dt*(.2+i*.13);r.rotation.z+=dt*.12;});this.coreSphere.position.y=2+Math.sin(this.clock*1.2)*.08;this.machines.forEach(m=>{m.userData.rotor.rotation.z+=dt*(.5+Math.log2((m.userData.level||0)+1)*.3);});this.animators.forEach(a=>{if(a.kind==='conveyor')a.obj.position.x=(this.clock*.8+a.offset)%10-5;else if(a.kind==='npc'){a.obj.position.x=a.baseX+Math.sin(this.clock*.2+a.offset)*.6;a.obj.rotation.y=Math.sin(this.clock*.15+a.offset)*.3;}else if(a.kind==='laser')a.obj.rotation.y=this.clock*.9+a.offset;else a.obj.rotation[a.axis]+=dt*a.speed;});}
 this.shards.forEach(m=>{m.rotation.y+=dt*.8;m.position.y=.8+Math.sin(this.clock*2+m.userData.shard)*.15;});this.droneGroup.children.forEach((d,i)=>{const a=this.clock*.6+i*2;d.position.set(this.player.x+Math.cos(a)*1.3,this.player.y+1.7+Math.sin(this.clock*2+i)*.15,this.player.z+Math.sin(a)*1.3);d.rotation.y=-a;});this.workerGroup.children.forEach((d,i)=>{const a=this.clock*.18+i;d.position.set(28+Math.cos(a)*6,0,Math.sin(a)*6);d.rotation.y=-a;});this.particles=this.particles.filter(p=>{p.life-=dt;p.m.position.addScaledVector(p.v,dt);p.v.y-=dt*3;if(p.life<=0){this.effectGroup.remove(p.m);return false;}return true;});this.pulseScale=Math.max(0,this.pulseScale-dt*1.3);this.core.scale.setScalar(1+this.pulseScale);
 if(this.arena==='parkour'){const p=this.parkourPlatforms[3],old=p.x;p.x=p.baseX+Math.sin(this.clock)*1.1;p.mesh.position.x=p.x-108;if(this.grounded&&Math.abs(this.player.y-p.y)<.05&&Math.abs(this.player.x-old)<p.w/2&&Math.abs(this.player.z-p.z)<p.d/2)this.player.x+=p.x-old;}
 if(!this.arena){const a=AREAS.find(a=>Math.abs(this.player.x-a.x)<11&&Math.abs(this.player.z-a.z)<11);if(a&&a.id!==this.zone){this.zone=a.id;this.state.emit('zone',a.name);}}
 this.pick();Object.assign(this.state.s.position,{x:this.player.x,y:this.player.y,z:this.player.z,yaw:this.yaw,pitch:this.pitch});if(settings.bloom&&settings.quality!=='low')this.composer.render();else this.renderer.render(this.scene,this.camera);
 }
}
